### ISSUE TITLE
antsApplyTransformsToPoints doesnt apply non linear transformation ?

### ISSUE THREAD

**Issue by celinede** [ANTsX/ANTs#1023]
Hi,

I have an issue with antsApplyTransformsToPoints.
I have previously done a SyN registration between two 2D images and I would like to transform the coordinates from the fixed images to the ones of the original moving space. So I apply the inverse transformation doing:

`antsApplyTransformsToPoints -d 2 -i coord.csv -o coord_output.csv -t [sub_syn_0GenericAffine.mat,1] -t sub_syn_1InverseWarp.nii.gz`

What I observe is that if I remove the `-t sub_syn_1InverseWarp.nii.gz` the coordinates that I get remain the same however there seem to be some non linear transformations which should be taken into account. And currently the coordinates that I get are in the area of my landmarks but not very precise.

I have attached my inputs if you want to give it a try. [testdata.zip](https://github.com/ANTsX/ANTs/files/4770920/testdata.zip)

Please let me know if you see anything that I might be doing wrong.

Céline

**Comment by ntustison** [comment]
The input coordinates and output coordinates are different when I run your command:

```
(base) ntustison@Figuring testdata % more coord.csv       
x,y,z
14.5411,7.34237,0
12.9972,5.88826,0
12.3151,8.29382,0
5.17018,8.36563,0
2.87232,7.6296,0
4.59571,6.2832,0
14.5411,7.34237,0
12.9972,5.88826,0
12.3151,8.29382,0
5.17018,8.36563,0
2.87232,7.6296,0
4.59571,6.2832,0
(base) ntustison@Figuring testdata % more coord_output.csv                                                                                
x,y,z
14.4938,7.53295,0
12.9521,6.06802,0
12.2613,8.45817,0
5.10512,8.45619,0
2.80608,7.69907,0
4.53643,6.3751,0
14.4938,7.53295,0
12.9521,6.06802,0
12.2613,8.45817,0
5.10512,8.45619,0
2.80608,7.69907,0
4.53643,6.3751,0

```

**Comment by celinede** [comment]
I meant if I do once the command 
`antsApplyTransformsToPoints -d 2 -i coord.csv -o coord_output.csv -t [sub_syn_0GenericAffine.mat,1] -t sub_syn_1InverseWarp.nii.gz`
and once 
`antsApplyTransformsToPoints -d 2 -i coord.csv -o coord_output.csv -t [sub_syn_0GenericAffine.mat,1]`
I get in both cases the same result

**Comment by ntustison** [comment]
It looks like your points exist outside the domain of the inverse warp field.

**Comment by celinede** [comment]
I don't really understand how that can happen ?
The points that I am trying to transform are not on the edges of the image and warp is not supposed to move them too much either.

**Comment by gdevenyi** [comment]
Is this perhaps the RAS vs LPS issue?

**Comment by ntustison** [comment]
Take a look at your inverse warp field in ITK-SNAP.  Your ITK point coordinates are all negative and I'm guessing your points are in Nifti coordinates.  You should work through the [chicken example](https://github.com/stnava/chicken) and adapt your scenario accordingly.

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians#transforming-a-point-set

The warps you use to deform a point set are the opposite to what you would use to warp an image. So to take points in the fixed space to the moving space, you need the forward warps. 

The order is reversed because when you resample a moving image into the fixed space, what actually happens internally is that a point set in the fixed space (a grid with points at the center of fixed space voxels) is warped to the moving space to compute the interpolated values of the moving image on the fixed image grid.

Thus the forward warps actually move a point set from fixed to moving space. We only call them forward warps because the most common use case is to resample the moving image to fixed space. But when you are applying the transforms to points directly, rather than images, you use the forward warps to take your points from fixed to moving space.

The other common problem, as discussed above, is the definition of coordinates. The points need to be specified in ITK coordinates, not NIFTI. The Wiki page has some links to help with this.

**Comment by celinede** [comment]
thank you very much for your help everyone, it seems to work once I use the ITK coordinates and the forward transformations. 
Is there any pre-made function for converting coordinates voxel based to ITK coordinates or nifti-world coordinates to ITK coordinates ?

**Comment by ntustison** [comment]
Not in ANTs but you might want to ask over at the ITK-SNAP discussion/help forum.

**Comment by gdevenyi** [comment]
@celinede since the conversion is RAS -> LPS generally, you can just do -x, -y, z to  convert to-from.

**Comment by cookpa** [comment]
ANTsR will transform an index coordinate to ITK physical coordinates, given an index coordinate (LPS) you can convert to physical space with the `antsTransformIndexToPhysicalPoint` function. Example here

https://github.com/ANTsX/ANTsR/wiki/MNI-Coordinates-in-ANTsR-(and-ANTs)

**Comment by celinede** [comment]
Thank you very much for your help ! then I'll just multiply my x and y by -1 since I mainly work in python
