### ISSUE TITLE
ITK PR which may impact how ANTs handles NIFTI files

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#1031]
Proposal to use the sform if it is labelled as being the SCANNER coordinate system:
https://github.com/InsightSoftwareConsortium/ITK/pull/1868

This may impact future data loading and some documentation.

**Comment by cookpa** [comment]
I hope this will improve precision and further reduce the inputs not in physical space errors.

**Comment by hjmjohnson** [comment]
> I hope this will improve precision and further reduce the inputs not in physical space errors.

@cookpa That is exactly why this change is being put forward!   This is the crux of that problem!

**Comment by cookpa** [comment]
I've looked at the code a bit more. If I understand correctly, the intent of the PR is to enable a new use case where a pure rotation is inserted into the sform, enabling closer agreement with the DICOM orientation.

But most data from converters like dcm2niix is still going to use qform because the sform matrix will include voxel scaling and / or a non-zero offset, and the test for orthogonality of sto_xyz will be false.

Also, any derived data is going to be read with qform because when the NIFTI file is written back out, the sform will contain the voxel scaling and offset. 

So I think most ANTs users are still going to be relying on qform, except in the case where voxels are 1mm isotropic and the offset is zero.

**Comment by hjmjohnson** [comment]
@cookpa You are correct!  I forgot that pixdim is not used for "sform" formats.  I need to remove the origin and spacing for the orthonormal testing!  I feel silly for missing this.

**Comment by cookpa** [comment]
Great! I was a bit concerned that normalizing out the spacing might re-introduce precision problems, but if you can do it, it would make sform much more widely useable.

**Comment by hjmjohnson** [comment]
This has been included in ITK now.

**Comment by cookpa** [comment]
Thank you @hjmjohnson.

To do for ANTs:

1. Test some more
2. Re-write Wiki
3. Bump ITK version (perhaps with next ANTs minor release)

**Comment by cookpa** [comment]
Updated code now integrated and documented, sform is preferred over qform where sensible.
