### ISSUE TITLE
Different resolution

### ISSUE THREAD

**Issue by namhoangle** [ANTsX/ANTs#1055]
I have several brain images with different resolution. I want to do registration in following cases and wonder if the results are sensible:

1. Case 1: I want to register Image2 with higher resolution (256x256x26) to Image1 with lower resolution (448x448x38)
2. Case 2: to register Image1 with lower resolution to Image2 with higher resolution
3. Will the registration make sense if I pad background values, i.e 0, to every dimension of the images?

**Comment by cookpa** [comment]
You can pad, and it can improve performance if you do so because the deformation is constrained to be zero at the edge of the image volume. So if your images fill the entire FOV, it's good to pad.

However, there's no requirement that the fixed and moving images in `antsRegistration` have exactly the same dimensions. What matters is that they overlap in physical space. 

You can assess this visually by loading both images into ITK-SNAP

https://github.com/ANTsX/ANTs/wiki/Using-ITK-SNAP-with-ANTs

If the images don't overlap well in physical space, you can use one of the ANTs initialization features. In `antsRegistration`, you can use the -r option to align by centers of mass or by the geometric image centers. If that's not good enough, you can use the `antsAI` command to search rotations and translations about the COM.

**Comment by namhoangle** [comment]
Thanks!

I'm considering register MRI images to CT ones. Will the registration make
sense if they are of different imaging modalities?

Nam

**Comment by namhoangle** [comment]
![image](https://user-images.githubusercontent.com/61637441/91017578-1062b600-e5b4-11ea-834b-ace97a404105.png)

**Comment by namhoangle** [comment]
![image](https://user-images.githubusercontent.com/61637441/91017578-1062b600-e5b4-11ea-834b-ace97a404105.png)

**Comment by cookpa** [comment]
Intermodality registration can work, but sometimes the defaults need adjusting. For example, the center of mass alignment for registration might not always be appropriate across modalities. To align MR to CT I would try to verify a good initializaiton, and then proceed with a mutual information metric.

https://github.com/ANTsX/ANTs/wiki/Tips-for-improving-registration-results
