### ISSUE TITLE
Weird antsApplyTransforms results 

### ISSUE THREAD

**Issue by lmidriganciochina** [ANTsX/ANTs#1056]
Hi, I am trying to run antsApplyTransforms to transform functional (time series) data to MN1 (2mm) template. 
I have registered my T1 to the mean_BOLD. 
          antsRegistrationSyN.sh -d 3 -f $T1_im -m $Template -o T1_2_Template_ -t s -p f -j 1 
Also, registered the T1 to Template. 
           antsRegistrationSyN.sh -d 3 -f $T1_im -m $mean_bold1 -o ${nm1}_T1_2_T2Mean_ -t s -p f -j 0
and I got the transforms. 
I am running antsApplyTransforms with 
         
antsApplyTransforms -d 3 -e 3 -o ${nm1}_bold2template.nii.gz -r $Template -i $EpiIm1 -n BSpline[5] -t T1_2_Template_1Warp.nii.gz -t T1_2_Template_0GenericAffine.mat -t ${nm1}_T1_2_T2Mean_1Warp.nii.gz -t ${nm1}_T1_2_T2Mean_0GenericAffine.mat  -v 1
I am getting a strange looking image.  I am wondering if someone can point me to what I am doing wrong?

**Comment by cookpa** [comment]
I think your `antsApplyTransforms` call would work as written if you had run the registration with `$Template` as the fixed image, rather than the moving. As it is, I think you need to replace

`-t T1_2_Template_1Warp.nii.gz -t T1_2_Template_0GenericAffine.mat`

with

` -t [ T1_2_Template_0GenericAffine.mat , 1 ] -t T1_2_Template_1InverseWarp.nii.gz`

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

**Comment by lmidriganciochina** [comment]
Thank you so much for the fast and helpful reply! I will re-run the registration, I did mean to have the Template as the fixed image :( .

**Comment by lmidriganciochina** [comment]
This worked.  I am so thankful!
