### ISSUE TITLE
Can't get antsApplyTransforms to resample 4D to template space

### ISSUE THREAD

**Issue by sgiavasis** [ANTsX/ANTs#106]
Hello,

I'm using antsApplyTransforms to warp a 3D image + timeseries to a template. Here is my command, broken up by parameter:

antsApplyTransforms 

--default-value 0 

--dimensionality 3 

--input <4D image>

--input-image-type 3 

--interpolation Linear 

--output <output name> 

--reference-image <2mm template> 

--transform transform2Warp.nii.gz 

--transform transform1Affine.mat 

--transform transform0Rigid.mat 

--transform func_to_anat_affine.txt

It works, sees all of the transforms properly, and begins to apply the warp to each volume:

Interpolation type: LinearInterpolateImageFunction
  Applying transform(s) to time point 0 (out of 124).
  Applying transform(s) to time point 1 (out of 124).
  Applying transform(s) to time point 2 (out of 124).
  Applying transform(s) to time point 3 (out of 124).
     .... etc.

At the end, it completes successfully and I get my output image - an image that looks properly warped to the template, except it is still in subject space resolution, despite the fact that the template I am using is 2x2x2.

When I run this exact command on a 3D image (and use input_image_type of 0 instead of 3), it actually gets resampled to 2x2x2 properly.

I would appreciate any thoughts. Thanks!

SG

**Comment by michaelbernier** [comment]
Hello!

I have the exact same problem; however, I updated to the latest release of ANTs (pulled yesterday, version up to date) and the problem is still occurring.. If I register a functional 3d map on my template, it is fine, but when it is the functional timeseries, the resampling is messed up (voxel size stay the same, but FOV extend is padded)

Func 3D Map:
R-to-L extent:   -96.000 [R] -to-    96.000 [L] -step-    1.000 mm [193 voxels]
A-to-P extent:   -96.000 [A] -to-   132.000 [P] -step-   1.000 mm [229 voxels]
I-to-S extent:   -78.000 [I] -to-   114.000 [S] -step-     1.000 mm [193 voxels]

Func 4D Timeseries:
R-to-L extent:  -624.000 [R] -to-    96.000 [L] -step-     3.750 mm [193 voxels]
A-to-P extent:  -723.000 [A] -to-   132.000 [P] -step-    3.750 mm [229 voxels]
I-to-S extent:   -78.000 [I] -to-   498.000 [S] -step-        3.000 mm [193 voxels]

Any suggestions?

**Comment by stnava** [comment]
note that this issue was closed/resolved.  that is because the bug was
fixed.

if there is still a bug, you need to share a reproducible example.  this
includes data, code + the details of ants version, what you installed etc.


brian

**Comment by stnava** [comment]
meant - if you want to convince us that there is still a bug ...


brian
