### ISSUE TITLE
Question about AntsRegistration

### ISSUE THREAD

**Issue by CarolineBao** [ANTsX/ANTs#1066]
I'm using antsRegistration to match the one image to another, but the output is very warped. I tried running the antsRegistration call without the SyN part and don't see the problem, so I'm thinking to adjust some of the SyN parameters and was wondering if I could get some guidance on how to go about doing that.

Code:
antsRegistration \
        --float 1 \
        --collapse-output-transforms 1 \
        --dimensionality 3 \
        --initial-moving-transform [dsurqec_15micron_masked.nii,ambmc_15micron.nii, 1 ] \
        --initialize-transforms-per-stage 0 --interpolation Linear --output [ ambmc2dsurqec_, ambmc2dsurqec_15micron.nii ] \
        --interpolation Linear \
        \
        --transform Rigid[ 0.5 ] \
        --metric MI[dsurqec_15micron_masked.nii,ambmc_15micron.nii, 1, 64, Random, 0.1 ] \
        --convergence [ 400x400x400x200, 1e-9, 10 ] \
        --smoothing-sigmas 3.0x2.0x1.0x0.0vox \
        --shrink-factors 10x4x2x1 \
        --use-estimate-learning-rate-once 0 \
        --use-histogram-matching 1 \
        \
        --transform Affine[ 0.1 ]\
        --metric MI[dsurqec_15micron_masked.nii,ambmc_15micron.nii, 1, 64, Regular, 0.1 ] \
        --convergence [ 400x200, 1e-10, 10 ] \
        --smoothing-sigmas 1.0x0.0vox \
        --shrink-factors 2x1 \
        --use-estimate-learning-rate-once 0 \
        --use-histogram-matching 1 \
        \
        --transform SyN[0.25,3,0] \
        --metric CC[dsurqec_15micron_masked.nii,ambmc_15micron.nii,1,4] \
        --convergence [100x70x50,1e-6,10] \
        --shrink-factors 8x4x2 \
        --smoothing-sigmas 3x2x1vox \
        \
        --winsorize-image-intensities [ 0.05, 0.95 ] \
        --write-composite-transform 1 \
        --verbose

Files: [dsurqec_15_micron_masked.nii](https://drive.google.com/file/d/1WYqMEJeWJkOhPBzDibzIGNVWh7GVNith/view?usp=sharing) [ambmc_15_micron.nii](https://drive.google.com/file/d/1dlegg6yAhnmO1GLPBzfMwy0K5mM85Zbe/view?usp=sharing)

Input files (fixed image on the left):
<img width="1757" alt="Screen Shot 2020-08-12 at 11 04 36 PM" src="https://user-images.githubusercontent.com/37222366/90099872-48cede00-dcf0-11ea-80ae-25577e4d9821.png">

Output:
<img width="923" alt="Screen Shot 2020-08-14 at 9 36 27 AM" src="https://user-images.githubusercontent.com/37222366/90272471-53819400-de12-11ea-8d9b-3516049e58e1.png">

Thank you!

@TheChymera

**Comment by cookpa** [comment]
If the affine part looks good, you can run it once and then pass that transform to the command with SyN using `-r`. This is useful both to save time and because it makes it easier to then run with `--write-interval-volumes` to write out intermediate volumes during the registration, so you can see the progress of the deformation.

Another general point is to be careful about the `-w` option. You are clipping the top 5% of image intensities which might be fine, but you have to assess this on your data. You don't want to lose useful contrast.

To reduce deformation, you can do fewer iterations, reduce the step size (first SyN parameter) or add regularization (second SyN parameter). You can also increase the size of the CC radius in the metric, but this will increase computation time.
