### ISSUE TITLE
N4BiasFieldCorrection diffusion weighted data set results in 'brain on fire'

### ISSUE THREAD

**Issue by MargotHeijmans** [ANTsX/ANTs#1127]
Hi all,

For an MRI dataset of almost 100 people we collected diffusion weighted data. In the analysis pipeline, we also use the N4BiasFieldCorrection. For all of the datasets this works out perfectly, except for 1.

This is the command line we use.

N4BiasFieldCorrection -d 4 -i INPUTFILE -s 2 -c [100x100x100x100,0.0000000001] -o OUTPUTFILE

As is shown in the picture below, when scrolling through the 66 volumes of this output file, the brain is lighting up from the bottom.

It starts pretty small, and becomes bigger and bigger when going through the volumes.
![image](https://user-images.githubusercontent.com/37331479/103746971-32f4e900-5002-11eb-9edc-2b5552d588df.png)
![image](https://user-images.githubusercontent.com/37331479/103747070-5cae1000-5002-11eb-85f2-1fbbb0a9daf6.png)

It is strange that this is only the case for 1 specific file. We run the whole analysis pipeline for this person again, including the N4 step, and again this strange light shows up.

Does anyone has seen this before? Or does anyone has an idea how this can be explained?

Best,
Margot

**Comment by ntustison** [comment]
Hi Margot,

N4 over four dimensions isn't used much and so it's not well-understood.  From N4 and earlier N3 work, we find that the "spline distance" should probably be between 50-200 mm for brain applications.  However, we don't have that same experience and intuition for the temporal distance.  Since N4 will simply treat the voxel spacing in that fourth dimension exactly like the spatial dimensions 1-3, one would have to modify the temporal voxel spacing so that it makes sense and so it could be that you're seeing those effects.  Also, you really should set that spline distance explicitly as the default value isn't optimal for most scenarios.

Nick

**Comment by cookpa** [comment]
I would suggest something similar to what mrtrix does. Run N4 on the average b=0 image, then apply the bias field to the whole DWI series.

**Comment by cookpa** [comment]
Since this has come up a few times.

https://github.com/ANTsX/ANTs/wiki/N4BiasFieldCorrection

See the note about `dwibiascorrect` from mrtrix - they use parameters quite different to the N4 defaults. I'd use those as a starting point for diffusion data.

**Comment by ntustison** [comment]
This is great, @cookpa.  Thanks.

**Comment by MargotHeijmans** [comment]
Thanks for your help!
