### ISSUE TITLE
Extracting Surface Area from DiReCT (KellyKapowski)

### ISSUE THREAD

**Issue by jckim80** [ANTsX/ANTs#1188]
Hi Nick and Brian,

I am analyzing the cortical thickness of nonhuman primates using KellyKapowski command.
Are there any programs or ANTs functions to estimate regional surface areas (like FreeSurfer) using the outputs of KellyKapowski?

Thank you!

Jeongcul.

**Comment by stnava** [comment]
I've  been interested in that for a long time and played with it a bit at the voxel level and we have some methods based on differential geometry but I don't have much confidence in any of them, though it could be worth revisiting.   even the freeusrfer "area" function is not really that.  it's just an approximation - the ratio of one triangle's area to another (maybe I am mistaken but that's my recollection).  turns out that, mathematically, this is difficult to estimate in a well-posed manner.   an easy alternative is to use a sliding window around the cortex and measure the volume of cortex  as well as its thickness.  then area is well-defined.

the differential geometry approach is based on using local gradient-based frames to approximate the image as a surface at every voxel.  the instantaneous "area" is then related to the riemannian metric.  the validity of this estimate is questionable, though.

**Comment by jckim80** [comment]
Thank you so much for your reply. I found Issue #1013 addresses a similar issue. The command LabelGeometryMeasures estimates ROI surface area instead of cortical surface area. But, I think that might be helpful.
