### ISSUE TITLE
 Error: Inputs do not occupy the same physical space! 

### ISSUE THREAD

**Issue by enrit** [ANTsX/ANTs#1219]
Hi All, 

I am getting the following error when running the following - 
--------------------------------------------------------------------------
LesionFilling 3 t1.nii.gz lesions.nii.gz t1_lesionfilled.nii.gz
Number of lesions: 6
libc++abi: terminating with uncaught exception of type itk::ExceptionObject: /Applications/ANTs/build/staging/include/ITK-5.2/itkImageToImageFilter.hxx:220:
itk::ERROR: itk::ERROR: MaskImageFilter(0x7fd39f4044b0): Inputs do not occupy the same physical space! 
InputImage Origin: [8.3020264e+01, 9.7875153e+01, -1.5158517e+02], InputImage_1 Origin: [8.3020248e+01, 9.7875153e+01, -1.5158517e+02]
	Tolerance: 9.9997234e-07

Abort trap: 6
--------------------------------------------------------------------------

Can someone suggest how to fix this ?

Many thanks

Rito

**Comment by gdevenyi** [comment]
Try using antsapplytransforms to resample the mask like the t1 (-r) something about the headers appears to be outside the allowable tolerance

**Comment by cookpa** [comment]
There's a few options here.

**SetOrigin**

Use `SetOrigin` to set the origin of both images directly. It should be consistent between images of the same dimensionality, so it should produce the same header on t1 and lesions.


**antsApplyTransforms**

`antsApplyTransforms` will resample the moving image into the reference image space. Use `-n NearestNeighbor` for this use case (ie, a tiny change).


**CopyImageHeaderInformation**

This attempts to copy the origin (or other header info, see usage) from a reference to a moving image. It doesn't resample the data.


None of these methods can preserve full precision of the header information, because they all involve reading a NIFTI header (stored as single-precision floats) and converting the information into the internal ITK data structure (double precision), and then writing them back out in NIFTI format again. This is unfortunately a lossy procedure. 

Usually, `CopyImageHeaderInformation` gets images consistent to within the tolerance. `SetOrigin` is the most robust because you can set both the images to the same thing, but sometimes it might be undesirable to modify the t1 (eg, you have other things you want to sample in t1 space).

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/wiki/Inputs-do-not-occupy-the-same-physical-space
