### ISSUE TITLE
Suggestions for next ANTs release

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#1270]
Since we are currently building against a release ITK version, and have resolved a number of issues affecting external builds, I was thinking to bump the version to 2.4.0 in the next release.

Anything we need to fix before that?

Tagging @ntustison and @gdevenyi but suggestions welcome from all.

**Comment by gdevenyi** [comment]
Here's my ideas for things I would like (and could possibly assist with)
1. Packages for major distros using cpack (I do this with minc-toolkit using these Dockerfiles and scripts, https://github.com/BIC-MNI/build_packages )
2. Fixing cmake so that "make install" in the top-level directory works (I don't know how to do that)
3. Addressing #397
4. Performing a purge of files in the repo which aren't actually compiled used
5. 1+2 could enable a conda-forge package

None of these are "needs" but rather "wants" from me with my sysadmin/reproducable computing hat on.

**Comment by cookpa** [comment]
Thanks @gdevenyi . 

I have attempted #2 but couldn't make it work. #3 seems do-able but would need some testing and review of the scripts to not fail with `bash -e`. Related: #4, there's also a bunch of scripts that haven't been updated in a long time, and might be sensible to deprecate somehow.
