### ISSUE TITLE
Template Construction Error

### ISSUE THREAD

**Issue by AndreaZito** [ANTsX/ANTs#1276]
Dear all, 

I used the antsMultivariateTemplateConstruction2.sh script to generate a template for lizard brain MRI images. But for every trial, we get the same error:

The command we ran was:
“antsMultivariateTemplateConstruction2.sh -d 3 -r 1 -o OUTPUT A*.nii”

It can do the rigid body registration of the inputs, but it fails when it starts to build the templates. This is the error we get:
“terminate called after throwing an instance of 'itk::MemoryAllocationError'
what():  /home/zitoa/ANTS/build/staging/include/ITK-5.2/itkImportImageContainer.hxx:192:
Failed to allocate memory for image.”

The dimensions of our images are 151x241x136. We ran the script for our original images, then converted our images from double precision to signed short to reduce the file sizes. For both types of our images, we got the same error.
We wanted to check if a basic registration could be done using “antsRegistrationSyNQuick.sh”, to see if there was something wrong with our images. But this was successful.

I am wondering if there are any ideas as to why this problem is occurring?

Thank you very much in advance for your help,

Sincerely,
Andrea

**Comment by gdevenyi** [comment]
Hi Andrea,

First you may find this other lizard MRI model interesting, https://onlinelibrary.wiley.com/doi/abs/10.1002/cne.24480

> We ran the script for our original images, then converted our images from double precision to signed short to reduce the file sizes. For both types of our images, we got the same error.

The input file type does not have an impact on the internal computation for ANTs tools, where everything is done in float or double. The default for antsMultivariateTemplateConstruction2 is float(see `     -e   use single precision ( default 1 )`

Given you're using the defaults otherwise, the template build is running a single registration at a time.

I have a suspicion, that since you're not using any initialization, that your FOVs of the inputs may not overlap much (or at all) making the effective model size much much larger. You can check that by looking that properties of the OUTPUTtemplate0.nii.gz file.

I would suggest either using one of your inputs as the option for the rigid starting target (`-r1 -z <IMAGE>`) or looking at trying my re-written https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction which has a robust initialization which includes cropping.

**Comment by AndreaZito** [comment]
Hello, 

Thank you very much for the reply! Sorry for responding late, I got caught up in exams.

I tried using one our images as a reference and checked the output file. It resulted in much better alignment, but still gave the same error. 

I next wanted to try your re-written antsMultivariateTemplateConstruction, but it requires some other installations. Do I have to install minc-tools and minc-tools-extras? Or could I just install the required scripts from minc-toolkit-extras?

If I have to install minc-tools and minc-tools-extras, I get a 'ERROR 404' from line 6 in https://github.com/CoBrALab/documentation/blob/master/minc-install.sh

Full error message:
```
wget -c http://ftp.us.debian.org/debian/pool/main/libj/libjpeg8/libjpeg8_8d-1+deb7u1_amd64.deb

--2021-12-27 21:57:29--  http://ftp.us.debian.org/debian/pool/main/libj/libjpeg8/libjpeg8_8d-1+deb7u1_amd64.deb
Resolving ftp.us.debian.org (ftp.us.debian.org)... 64.50.236.52, 64.50.233.100, 208.80.154.15, ...
Connecting to ftp.us.debian.org (ftp.us.debian.org)|64.50.236.52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-27 21:57:29 ERROR 404: Not Found.
```

**Comment by gdevenyi** [comment]
> Or could I just install the required scripts from minc-toolkit-extras?

Just the scripts.
