### ISSUE TITLE
antsApplyTransforms -e and -d flags clarification

### ISSUE THREAD

**Issue by tmspvn** [ANTsX/ANTs#1299]
Hi,
I would like to understand better how the -d and -e flags modify the behaviour of apply transform.

According to what I understood from [issues 873](https://github.com/ANTsX/ANTs/issues/873) and the [wiki](https://github.com/ANTsX/ANTs/wiki/Dimensionality-or-ImageDimension-option-in-ANTs) about the flags, -d specifies how the algorithm behaves with the input transform/s while the -e flags specify how the input image must be handled, but how exactly?.

Assuming the reference images have the same dim of the warp, correct me if am wrong:
`-d 4 -e 3` means a 4D warp applied to 4D image, volume matched?
`-d 3 -e 3` means 3D warp applied to 4D image, volume-wise? 
`-d 3 -e 2` means 3D warp applied to 4D image, volume-wise [again](https://github.com/ANTsX/ANTs/issues/873#issuecomment-541137458)?
`-d 3 -e 2` means 3D warp applied to 3D image?
`-d 2 -e 2` means apply 2D slice warp to 3D img, if so along which axis?

Let's say I have a 4D image with 3D warp and 3D reference image, should I use -d 3 -e 3 to apply the 3D transform to the 4D image? Or would this be an improper task and therefore I must make the 3D warp 4D by repeating it along the 4th dimension?

Thanks!

**Comment by cookpa** [comment]
Hi,

Here's how I think it goes:

`-d N` means the dimensionality of the warp, and implies an N-dimensional grid of N-dimensional warp vectors.

`-e M` means the type of moving image. 

`-e 0` is an N-dimensional grid of scalars. 
`-e 1` is an N-dimensional grid of N-dimensional vectors. 
`-e 2` is an N-dimensional grid of N-dimensional tensors. 
`-e 3` is an (N+1)-dimensional grid of scalars, the warp of dimension N is applied to each volume.
`-e 4` is an N-dimensional grid, with an arbitrary number of independent scalar components at each point. The warp is applied to each scalar independently.

Some special cases in your questions:

>-d 4 -e 3 means a 4D warp applied to 4D image, volume matched?

I think this would be `-d 4 -e 0`. It's a bit confusing because you are inputting a time series, but I think the `-e 3` exists for when your warps are applied sequentially to each volume. If you do a 4D registration, you are resampling across time as well as space. @ntustison do I have this correct?


>-d 2 -e 2 means apply 2D slice warp to 3D img, if so along which axis?

`-e 2` is a tensor image. I don't think you could apply a 2D warp to a 3D scalar image. You would do in-plane registration with `antsRegistration -d 2` and then call `antsApplyTransforms -d 2 -e 0`.

**Comment by gdevenyi** [comment]
This is definitely worth a wiki page once the best wording is decided on.
