### ISSUE TITLE
slight misalignement MNI ventricles to BOLD image

### ISSUE THREAD

**Issue by pinilorenzo** [ANTsX/ANTs#1463]
Hello,

I'm trying to register a specific MNI152 mask  to the native BOLD space using the following images and code: 

- native fMRI:                             BOLD_bet.nii.gz
- T1w brain extracted:                T1w_brain
- MNI152 template:                   MNI152_T1_1mm_brain
- MNI mask (to be registered):  ventriclesMNI_1mm

>> antsRegistrationSyNQuick.sh -d 3 -f MNI152_T1_1mm_brain.nii.gz -m T1w_brain.nii.gz -o T1w_2_MNI -t s
 
>> antsApplyTransforms -d 3 -o [CollapsedWarp.nii.gz,1] -t T1w_2_MNI1Warp.nii.gz -t T1w_2_MNI0GenericAffine.mat -r MNI152_T1_1mm_brain.nii.gz

This code just needs to extract the 'tr' info used below
>> tr=`PrintHeader rsfMRI_subj1.nii.gz | grep "Voxel Spac" | cut -d ',' -f 4 | cut -d ']' -f 1` 

>> ImageMath 3 4DCollapsedWarp.nii.gz ReplicateDisplacement CollapsedWarp.nii.gz 1 $tr 0

>> antsApplyTransforms -d 3 -o BOLD_TO_MNI.nii.gz -t 4DCollapsedWarp.nii.gz -t T1_2_MNI1Warp.nii.gz -r MNI152_T1_1mm.nii.gz -i BOLD_bet.nii.gz

>> antsApplyTransforms -d 3 -o ventricles_MNI_2_BOLD.nii.gz -t [T1w_2_MNI0GenericAffine.mat,1] -t [T1w_2_MNI1InverseWarp.nii.gz] -r BOLD_bet.nii.gz -i ventriclesMNI_1mm.nii.gz -n NearestNeighbor

BOLD_TO_MNI.nii.gz looks accurate, while ventricles_MNI_2_BOLD.nii.gz is slightly misaligned, with few voxels outside the ventricles observed overalpping the mask to the BOLD image.

Any tips?
Thanks
Lorenzo

**Comment by cookpa** [comment]
There's no BOLD to T1w registration in here. Are they already co-registered?

If not, you will need a step that does that.

If so, then your command looks good, though I would replace NearestNeighbor with GenericLabel. Also, you can use the `-e` option in `antsApplyTransforms` to warp time series data to a 3D reference space, without the ReplicateDisplacement step.

The BOLD image isn't used anywhere in the registration, so if there's any misalignment it's due to either the T1w and BOLD not being aligned, or the T1w and MNI not being aligned, or the original segmentation in the MNI space over or under segmenting the ventricles. And combinations of all of these.

Even if the T1w <-> MNI registration is very good, it's possible that the final mask in BOLD space will suffer from aliasing. The voxels in BOLD space are probably bigger than in T1w / MNI, and there are likely more partial volume voxels around the ventricles. The effects of this may well be more visually obvious when resampling a hard segmentation to BOLD space, than when resampling a blurrier BOLD image into MNI space.

**Comment by pinilorenzo** [comment]
Thanks for your quick answer

I guess this misalignment is linked with the BOLD to T1w registration.
Could you suggest me the best way (and codes) to include the BOLD to T1w registration step in the above code?

Thanks a lot
Lorenzo
