### ISSUE TITLE
Random seed seems to have no effect on ANTs with SyN and CC

### ISSUE THREAD

**Issue by gandreadis** [ANTsX/ANTs#1470]
**Describe the problem**

I'm using the ANTs `antsRegistration` CMD-line executable, with SyN as transform and CC as metric. I'm using the `--random-seed` option to set the value, but no matter what I set it (0, which should use system time, or any positive non-0 value, which should set that as seed), the output and metric/convergence values over time are always exactly the same. I've also tried the `ANTS_RANDOM_SEED` environment variable, but no success with this, either. 

Following the wiki, I've also tried to specify a sampling strategy for CC (`random` with percentage `[0-1]`), but this does not change the result. I've used `--verbose` to verify that this sampling strategy is indeed set.

**To Reproduce**
Use the `antsRegistration` script with two images, using the SyN transform with CC, and try to set the random seed with `--random-seed [int]`.

**System information (please complete the following information)**

 - OS: Linux CentOS
 - OS version: Stream release 8
 - Type of system: HPC cluster

**ANTs version information**
 - ANTs code version: v2.4.2.post39-gbaa2bd1
 - ANTs installation type: Compiled from source

**Additional information**

**Comment by gdevenyi** [comment]
Have you read https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues

**Comment by stnava** [comment]
short story - this is expected as CC is not randomized

**Comment by gandreadis** [comment]
@stnava That explains it, thanks. Is it possible to use a different sampling strategy with CC?

**Comment by cookpa** [comment]
This is a bit confusing because the metric sampling strategy is an option of the metric (eg, CC) in `antsRegistration`, but it's a property of the registration type (eg, Rigid, SyN) in ITK.

If you choose any sampling strategy other than  "None", the registration method **may** use random sampling to choose and/or perturb the points. This leads to variation in results. But the SyN method doesn't do that.

You can make CC non-deterministic with another transform, eg `-t Affine[0.1] -m CC[ fixed, moving, 1, Random, 0.5 ]` will be non-deterministic, because the affine registration method calls [ImageRegistrationMethodv4:SetMetricSamplePoints()](https://github.com/InsightSoftwareConsortium/ITK/blob/d19e77480914bc51a09608a7e78dfb5bc5457844/Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx#L919). I don't know if any of the deformable methods do.

**Comment by gandreadis** [comment]
@cookpa Thanks for the elaboration, that makes it clear. Maybe something to this effect could be added to the respective wiki entries about reproducibility? Because I can't imagine being the only one to only use the SyN stage (without affine) and trying to set the random seed parameter.

**Comment by cookpa** [comment]
Yes, I will try to explain it better

**Comment by cookpa** [comment]
Update, I tried to improve the wiki page

https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues

I looked at the code again and I think SyN is the only transform option that doesn't call [PrepareRegistrationMethod](https://github.com/ANTsX/ANTs/blob/cdabb0d4236bbc3ae091f28e64b02ae631f3bdab/Examples/itkantsRegistrationHelper.h#L902), so I think it's the only method that won't produce any variation with random subsampling in the metric.
