### ISSUE TITLE
Image-weighting in antsRegistration and antsRegistration_affine_SyN.sh

### ISSUE THREAD

**Issue by valeryozenne** [ANTsX/ANTs#1500]
Dear ANTs experts,

I'm looking for small advises related to the use of antsRegistration and antsRegistration_affine_SyN.sh from minc-toolkit-extras/.

# Aim

I wish to map an existing atlas on a home-made template. 

# Context

The brain template was built with antsMultivariateTemplateConstruction2.sh using MP2RAGE sequence at 150µm3 acquired in-vivo.

Here is a screenshot:

![Capture d’écran de 2023-02-21 14-16-37](https://user-images.githubusercontent.com/7050315/220355885-33fc6a4e-6f6d-4597-9624-73d055c77e8c.png)

The existing atlas is an in-vivo Microscopy (CIVM) mouse brain atlas from the https://www.civm.duhs.duke.edu/duke-CIVM-sup-mouse-brain-connectome. It includes
 - the labels
 - an anatomical image from Microscopy. 

Here is a screenshot:

![Capture d’écran de 2023-02-21 14-15-18](https://user-images.githubusercontent.com/7050315/220356431-00e75935-f3a8-48d5-b7fa-7a5a2d03ed25.png)

To register both, I used the minc-toolkit-extras/antsRegistration_affine_SyN.sh from @gdevenyi in two steps: affine then non-linear.
The input is multimodal and includes:

--moving: the label of the ventricles  
--fixed: a segmentation of the ventricles  
--moving: the anatomical image image from in-vivo Microscopy (CIVM)  versus
--fixed:  a negative MP2Rage sequence to get similar intensity

Here the exact command:
```
logCmd /home/vozenne/Dev/minc-toolkit-extras/antsRegistration_affine_SyN.sh  ${SKIP_NL_MODE}  ${FAST_MODE}  \
                                                                             --moving ${CIVM_LOW_RES_LAPLACIAN}  \
                                                                             --fixed ${MP2_REGRIDDED_ADD_NEG_LAPLACIAN_SKULL_MASKED}  \
                                                                             --moving ${CIVM_MASK_VENTRICULES_LOW_RES} \
                                                                             --fixed ${MASK_VENTRICULES_REGRIDDED_X10}  \
                                                                              ${CIVM_LOW_RES} ${MP2_REGRIDDED_MINUS_REVERSE_SKULL_MASKED} \
                                                                              ${REGISTRATION_FOLDER}/output_minc_fast_no_mask_skip_nl_extract_ -c -v


logCmd  /home/vozenne/Dev/minc-toolkit-extras/antsRegistration_affine_SyN.sh --skip-affine ${SKIP_NL_MODE}  ${FAST_MODE} --initial-transform ${TRANSFORM_INITIALE}  --moving ${CIVM_LOW_RES_LAPLACIAN} --fixed ${MP2_REGRIDDED_ADD_NEG_LAPLACIAN_SKULL_MASKED}  --moving ${CIVM_MASK_VENTRICULES_LOW_RES}  --fixed ${MASK_VENTRICULES_REGRIDDED_X10} ${CIVM_LOW_RES} ${MP2_REGRIDDED_MINUS_REVERSE_SKULL_MASKED} ${REGISTRATION_FOLDER}/output_minc_fast_no_mask_extract_ -c -v

```
After a battery of tests to adjust the contrast of inputs files, results seems ok but only at first glance, some discrepancies still exist for some structures like the ventricles (for some reasons, the ventricles are really small in the mouse atlas from microscopy)

Here is the screenshot:
![Capture d’écran de 2023-02-21 14-13-09](https://user-images.githubusercontent.com/7050315/220356982-1928f97f-32af-4418-b409-0ba94a371a5b.png)

Typically
![Capture d’écran de 2023-02-21 14-14-40](https://user-images.githubusercontent.com/7050315/220358780-a8a85e54-1105-4a40-93bb-be1a17c616ea.png)

# (naive) Question 1 

I would like to increase the "weight" for the --fixed and --moving corresponding to the ventricles label in order to improve the match  ?

Does changing the values of both labels (((fixed and ((moving)  from 1 to 1000 will change the weight in the "cost function of ANTsRegistration" ? 

# Question 2

If not, what would be the simplest way to adjust the weight of input images in antsRegistration_affine_SyN.sh  
or in case with antsRegistration.sh 

I'm doing a T1 mapping the thalamus nuclei, and I need a even more accurate match of well visible structure in the central region. 

Many thanks in advance for your help.
Valéry

**Comment by gdevenyi** [comment]
Hi,

First, its best to open an issue where the code exists, https://github.com/CoBrALab/minc-toolkit-extras the ANTs developers don't know anything about the insides of my registration script.

> I would like to increase the "weight" for the --fixed and --moving corresponding to the ventricles label in order to improve the match ?

You haven't provided images of all the input pairs for this to be answered definitively. It will cause that pair to be weighted higher during similarity calculations. The exact type of contrast the images give is also important.

> Does changing the values of both labels (((fixed and ((moving) from 1 to 1000 will change the weight in the "cost function of ANTsRegistration" ?

You can read about the specifics of the weight implementation here:
https://github.com/ANTsX/ANTs/wiki/Anatomy-of-an-antsRegistration-call#registration-stages

I have exposed weighting of image pairs here, https://github.com/CoBrALab/minc-toolkit-extras/pull/12 so that they're directly provided to the antsRegistration call, so they work like the linked document above.

Based on the small amount of images you have shown here, you may be violating the 1:1 voxel mapping expected during image registration, as some images appear to be skull-stripped, and some are not. I suggest making sure they are all skull stripped the same way to help here.

Finally, assumptions are made in various places about background intensity which your current MP2RAGE images may also violate, stripping could help here too.

**Comment by valeryozenne** [comment]
Hi,

Thanks for the fast answer. Sure, I close this issue and reopen it if needed on the CobraLab account.

I now see where is the weight in the Registration call. Thanks a lot for the new branch, I'm testing it.

I did the skull-stripping  before the call of antsRegistration_affine_SyN.sh, I forget to mention it. It is a requirement. 

Best,
Valéry
