### ISSUE TITLE
Regarding Inverse Warps

### ISSUE THREAD

**Issue by thomshaw92** [ANTsX/ANTs#1525]
Hi experts, 
I have a bunch of forward transforms (from moving.nii to fixed.nii) for which I deleted the inverse warp :( 
From reading through the forum (e.g., #326 , "most of the deformable methods do not have an analytical inverse" and "i doubt that the inverse can be computed on the fly.")

A few questions:
1) What would happen if I applied the inverse deformable transform to the forward transform? Is this not the inverse?
e.g., 
``` antsApplyTransforms -d 2 -i ForwardTransform.nii.gz -r input.nii.gz -t [ForwardTransform.nii.gz,1] -o Inverse.nii.gz ```

2) Can I calculate the inverse some other way using ANTs?

3) If I register fixed.nii -> moving.nii, is that warp the same as the inverse of moving -> fixed.nii?

Thanks for your help!

**Comment by gdevenyi** [comment]
SimpleITK wraps the InveseDisplacementField filter from ITK which can compute a numerical estimated inverse.

https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1InverseDisplacementFieldImageFilter.html

**Comment by cookpa** [comment]
1. It's negative because we're trying to approximate an inverse of the average transform, such that we can resample template_i from iteration i into the space of template_{i+1}. This is a first-order approximation ( #1172) and thus we only trust it for small steps. A larger step size will apply more deformation but doesn't necessarily get us closer to the optimal shape.

2. Composing the scaled transform multiple times lets each point take a curved trajectory using linear interpolation (ie, Euler's method). I think this is referred to in the DARTEL paper in the "Method" section. 

Note that in the DARTEL methods text, the scaling and squaring approach is to approximate \Phi_1, so they choose the scaling parameter 1/N such that \Phi_{1/N} can be composed to \Phi_1.

In ANTs, the default step size is 1/4 and it is composed four times, but this is coincidence, they are not linked in the same way.

**Comment by thomshaw92** [comment]
Thank you!
