### ISSUE TITLE
Multi modal registration results depend on the order of the metric specification when using MI

### ISSUE THREAD

**Issue by devDonnn** [ANTsX/ANTs#1544]
Hi, I'm running a multi-modal registration in a repro mode on T1w, T1c, T2 and FLAIR images as follows. Why the below two examples yield different warp fields? The only difference is that for the SyN stage I replace T1 to be the first image instead of the T1c. Isn't it supposed to be an average of all four registrations regardless of their order?

Case 1: 

```
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
export ANTS_RANDOM_SEED=21

antsRegistration --verbose 1 --dimensionality 3 --float 0 \
--collapse-output-transforms 1 \
--output [ tx_,tx_Warped.nii.gz, ] \
--interpolation Linear \
--use-histogram-matching 0 \
--winsorize-image-intensities [ 0.005,0.995 ] \
\
--initial-moving-transform [ 05/T1c.nii.gz,06/T1c.nii.gz,1 ] \
\
--transform Rigid[ 0.1 ] \
--metric MI[ 05/T1c.nii.gz,06/T1c.nii.gz,1,32,Regular,0.25 ] \
--convergence [ 1000x500x250x0,1e-6,10 ] \
--shrink-factors 8x4x2x1 \
--smoothing-sigmas 3x2x1x0vox \
\
--transform Affine[ 0.1 ] \
--metric MI[ 05/T1c.nii.gz,06/T1c.nii.gz,1,32,Regular,0.25 ] \
--convergence [ 1000x500x250x0,1e-6,10 ] \
--shrink-factors 8x4x2x1 \
--smoothing-sigmas 3x2x1x0vox \
\
--transform SyN[ 0.1,3,0 ] \
--metric MI[ 05/T1c.nii.gz,06/T1c.nii.gz,1,32] \
--metric MI[ 05/T1.nii.gz,06/T1.nii.gz,1,32] \
--metric MI[ 05/T2.nii.gz,06/T2.nii.gz,1,32] \
--metric MI[ 05/FLAIR.nii.gz,06/FLAIR.nii.gz,1,32] \
--convergence [ 100x70x50x0,1e-6,10 ] \
--shrink-factors 8x4x2x1 \
--smoothing-sigmas 3x2x1x0vox
```

Case 2:

```
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
export ANTS_RANDOM_SEED=21

antsRegistration --verbose 1 --dimensionality 3 --float 0 \
--collapse-output-transforms 1 \
--output [ tx_,tx_Warped.nii.gz, ] \
--interpolation Linear \
--use-histogram-matching 0 \
--winsorize-image-intensities [ 0.005,0.995 ] \
\
--initial-moving-transform [ 05/T1c.nii.gz,06/T1c.nii.gz,1 ] \
\
--transform Rigid[ 0.1 ] \
--metric MI[ 05/T1c.nii.gz,06/T1c.nii.gz,1,32,Regular,0.25 ] \
--convergence [ 1000x500x250x0,1e-6,10 ] \
--shrink-factors 8x4x2x1 \
--smoothing-sigmas 3x2x1x0vox \
\
--transform Affine[ 0.1 ] \
--metric MI[ 05/T1c.nii.gz,06/T1c.nii.gz,1,32,Regular,0.25 ] \
--convergence [ 1000x500x250x0,1e-6,10 ] \
--shrink-factors 8x4x2x1 \
--smoothing-sigmas 3x2x1x0vox \
\
--transform SyN[ 0.1,3,0 ] \
--metric MI[ 05/T1.nii.gz,06/T1.nii.gz,1,32] \
--metric MI[ 05/T1c.nii.gz,06/T1c.nii.gz,1,32] \
--metric MI[ 05/T2.nii.gz,06/T2.nii.gz,1,32] \
--metric MI[ 05/FLAIR.nii.gz,06/FLAIR.nii.gz,1,32] \
--convergence [ 100x70x50x0,1e-6,10 ] \
--shrink-factors 8x4x2x1 \
--smoothing-sigmas 3x2x1x0vox
```

**Comment by cookpa** [comment]
Changing the order of operations will alter the results, this is actually the reason the MI metric is nondeterministic with multiple threads - because the order in which the threads are combined is not consistent.

But there's an additional source of difference. The first metric determines things like the parameters of the virtual space (origin, spacing, direction, bounding box) and is also used to [initialize parameters for the optimization](https://github.com/ANTsX/ANTs/blob/8cc4f8a3683364e73f31982dbb6136589c34c9c3/Examples/itkantsRegistrationHelper.hxx#L1315-L1321). 

Normally, the input images would be in the same space (they **must** be aligned in physical space, but theoretically could differ in voxel space, eg different spacing). So I would suspect the biggest source of variation would the from the registration scale estimators.

How different are the results with the two different metric orderings?

**Comment by devDonnn** [comment]
Thank you for the answer, @cookpa. I have also tried the CC metric for the SyN stage and I get the same output regardless of the image order which is what I wanted.

**Comment by cookpa** [comment]
Thanks for the update
