### ISSUE TITLE
Feature Request: more verbosity for antsAI

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#439]
antsAI's --verbose option isn't particularly verbose, particularly in the area of showing progress.

It's tough to gauge when a call might be done with no output.

**Comment by cookpa** [comment]
I took a look at this since I was also running antsAI recently. Most of the work is done by an `itkMultiStartOptimizerv4` object, so there's little scope on the ANTs side to report progress. I know there is progress reporting code in ITK for voxelwise image processing, but I don't know of anything similar for optimizers.

**Comment by spinicist** [comment]
Potentially unhelpful comment - how does `antsRegistration` print progress if such infrastructure does not exist?

**Comment by cookpa** [comment]
> Potentially unhelpful comment - how does `antsRegistration` print progress if such infrastructure does not exist?

This was the way - extend itkCommand and add to the optimizer as an observer.

**Comment by gdevenyi** [comment]
Hurrah! Now I can (potentially) add this to my registration tool after some testing. Thanks!
