### ISSUE TITLE
Is there a maximal data size for template construction?

### ISSUE THREAD

**Issue by valette** [ANTsX/ANTs#470]
Hi, and thank you for the source code for ANTs! We hare currently comparing different methods for groupwise registration, and we have tried the antsMultivariateTemplateConstruction2.sh, with two groups:
- a set of 20 thoracic CT images of size 512x512x400
- a set of 83 thoracic CT images of size 512x512x400

We have obtained correct results in the case with 20 images, but the case with 83 images failed to converge. The template image is not consistent at all. Is ANTs limited in the number of images, or is the problem coming from our side?
Thanks again

**Comment by ntustison** [comment]
The increased cohort size shouldn't matter as template building involves pairwise registrations which shouldn't be loaded into memory simultaneously.  My first guess would be that one of your 83 images is not "correct."   But that's just a guess.  The screen dump should provide some indication of what's going wrong.

**Comment by valette** [comment]
Here are sample axial images after rigid registration (iteration 0):
![rigid](https://user-images.githubusercontent.com/303166/28370915-c8cc426e-6c9b-11e7-9ac0-509378a1589f.jpg)

and the final result (iteration 4):
![final](https://user-images.githubusercontent.com/303166/28370930-d0a21d7e-6c9b-11e7-9558-a8b192e1ddfb.jpg)

The subjects are quite different, and it seems that the average image quality is decreasing. Are we reaching the limits of the approach or did we miss something? The log is also attached to this post just in case... [log.txt](https://github.com/stnava/ANTs/files/1159350/log.txt)

Thanks for your help!

**Comment by ntustison** [comment]
Oh, I didn't see that you're doing lung CT.  Template building using ANTs scripts is fairly turnkey when it comes to head/brain MRI because the overall gross registration problem is easier than e.g., lung CT.  With lung CT the correspondence assumption is a bit more strained due to large image differences such as the body in the background.  Note that this applies generally to pairwise image registration.    

When I build such templates I'm usually interested in the lungs only so I first extract the lungs, run template building on the extracted lungs, and then apply the results of the template building to the original images.

**Comment by valette** [comment]
Actually, we are interested in registering the entire images without focusing on a specific organ. 
We want to include comparisons of groupwise registration approaches into an academic paper. 
As ANTs is able to register our 20 images, do you think we could easily tweak parameters to get better results with 83 images? We tried a bit but without success.
I am not sure that github is the right place for such discussions, but thanks again!

**Comment by ntustison** [comment]
The number of images doesn't matter.  Obviously I haven't seen the data but based on my experience with body CT, my guess is that the variance in intensity/shape in your cohort of 83 is much greater than the variance of 20 which is causing the registration issues.
