### ISSUE TITLE
Is ANTs or ITK able to handle complex valued data?

### ISSUE THREAD

**Issue by fluese** [ANTsX/ANTs#565]
I would like to use antsApplyTransforms to transform a complex valued NIfTI. The transform has been generated using antsRegistration on the magnitude data of the same dataset.

**Comment by fluese** [comment]
Thanks for the quick response, Brian!

After using the '-e vector' flag the output file has a dimension of 320x320x224x3 instead of 320x320x224 and isn't complex valued anymore. The value at, e.g., 160x160x112x1 is identical to 160x160x112x2 and 160x160x112x3. Therefore, it doesn't seem that the real and imaginary part have been split.

**Comment by spinicist** [comment]
Hi,
yes, `antsApplyTransforms` does not currently support complex-valued images directly.

The way I do this is to split the complex images into separate real & imaginary images using `fslcomplex` or my own tool (see `qicomplex` in http://github.com/spinicist/QUIT), apply the transform to the real & imaginary images, and then re-combine them. Do not apply transforms to magnitude and phase because the phase will get incorrectly interpolated across any +pi/-pi wraps.

If I follow Brian's logic, yes, you could directly interpret a complex-valued NIFTI as a 2 component vector NIFTI if you messed with header. However, I'm not aware of any existing tool to do this?

**Comment by cookpa** [comment]
I think you would need to treat the input data as a time series, and then it would be output as a time series. You would then need to convert back to complex type.

`antsApplyTransforms` expects vectors to be spatial vectors, and will attempt to transform them into physical space according to the moving image header. You don't want this for complex data.

@ntustison do I have this correct?

**Comment by stnava** [comment]
sorry, that's what i meant originally - for the data to be treated as
multi-channel.  not as a physical space vector.

maybe antsr would be easier, depending on how it default reads the image.


brian

**Comment by fluese** [comment]
I tried the idea of @stnava by splitting the real and imaginary part into a vector with the third dimension set zero. This did not seem to work properly. After applying the transform the values of the first two dimensions were the same, but the third one changed.

Using fslcomplex as suggested by @spinicist seems to allow splitting into magnitude and phase images, but doesn't conserve the real and imaginary part. Maybe I'm wrong though. The help isn't very helpful. Haven't had the chance to try out your quantitative tools.

@cookpa's idea, however, was successful. I split the real and imaginary part into a time series, applied the transform, and merged the real and imaginary part back to a complex value.

**Comment by ntustison** [comment]
@cookpa 

Yeah, a vector image undergoes a ["correction"](https://github.com/ANTsX/ANTs/blob/master/Examples/antsApplyTransforms.cxx#L291).
