### ISSUE TITLE
LabelOverlapMeasures seg faulting with any input

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#611]
Seems to be since ITKv5. I can't see any changes in the code that would cause this. The seg fault occurs here

https://github.com/ANTsX/ANTs/blob/49213bc987f5df5def9013b62c4bddaa6cb2240f/Examples/LabelOverlapMeasures.cxx#L53

**Comment by cookpa** [comment]
I could not compile with "Debug" set on my Mac. But I was able to use "RelWithDebInfo" and run lldb:

```
$ lldb -- LabelOverlapMeasures 3 cube.nii.gz cube.nii.gz labelOutput.csv
(lldb) target create "LabelOverlapMeasures"
Current executable set to 'LabelOverlapMeasures' (x86_64).
(lldb) settings set -- target.run-args  "3" "cube.nii.gz" "cube.nii.gz" "labelOutput.csv"
(lldb) run
Process 10011 launched: '/Users/pcook/bin/ants/bin/LabelOverlapMeasures' (x86_64)
LabelOverlapMeasures was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 10011 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x7ffeef3ffff8)
    frame #0: 0x000000010058b31c LabelOverlapMeasures`itk::ProcessObject::PropagateResetPipeline(this=<unavailable>) at itkProcessObject.cxx:1395 [opt]
   1392	    {
   1393	    if ( input.second )
   1394	      {
-> 1395	      input.second->PropagateResetPipeline();
   1396	      }
   1397	    }
   1398	}
Target 0: (LabelOverlapMeasures) stopped.
```

**Comment by ntustison** [comment]
Hey @cookpa , I can reproduce with a 2-D data set without the .csv option.  I wrote the itk::LabelOverlapMeasuresImageFilter but I don't know if the problem is there.  I have an old [version](https://github.com/ntustison/Utilities/blob/master/src/LabelOverlapMeasures.cxx) of ``LabelOverlapMeasures.cxx`` and I can compile that against the same ITKv5 and it works without a problem.  I'm investigating further and will let you know what I find.

**Comment by ntustison** [comment]
Okay, I think it's solved with [this commit](https://github.com/ANTsX/ANTs/commit/d7ff3fbe17af4571a68198826125bc5f09654a73).

**Comment by cookpa** [comment]
Thanks!
