### ISSUE TITLE
ANTs Optimizer: Confusion between learningRate and MaximumStepSizeInPhysicalUnits

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#617]
I'm reading through the optimizer code to understand how gradientStep affects registrations.

I've found the part in the code where the optimizer is initialized:
https://github.com/ANTsX/ANTs/blob/cf933a0b3aca1d1222271ac0d3f7e73d935939fb/Examples/itkantsRegistrationHelper.hxx#L1350-L1362

It looks like ConjugateGradientDescentOptimizerType is a superclass of the GradientDescentOptimizerv4Template.

Based on my reading of GradientDescentOptimizerv4Template along with the defaults listed on the antsRegistration it looks like the learningRate is going to be estimated and so gradientStep is actually effectively used as the MaximumStepSizeInPhysicalUnits setting for variable learning rate.

Is this correct? If so, does that mean that for example, fixed space of 1mm isotropic voxels and a subsample of 8, that a gradientStep of 0.1 means that each iteration has a maximum step size of 0.1*8mm?

Am I correct that depending upon "--use-estimate-learning-rate-once" the gradientStep option of transforms actually controls two different features?

**Comment by stnava** [comment]
i think you are confusing two things, probably due to unclear naming.
1) parameter scaling (SetDoEstimateLearningRateOnce ): adjust parameters per dimension (eg rotation translation in x or translation in y which "move" very differently with a given parameter update)
2) gradient calculation - given whatever's done above, adjust a single step size (eg gamma)
