### ISSUE TITLE
 WSL, Matlab and ANTs 

### ISSUE THREAD

**Issue by Hzl-git** [ANTsX/ANTs#646]
Hi everyone,

I'm currently getting my hands over the Windows Subsystem Linux (WSL) package in order to call & run ANTs functions directly in Matlab (as it is already doable on a Unix OS).

Things work perfectly fine within the WSL shell (here Ubuntu 16.04): I can run ANTs functionalities easily.

Although, the PATH variable is not the same in Matlab compared to the WSL shell: only ANTs path is missing, in spite of being "normally" set during ~/.bash_profile loading. Somehow, I can't export the path manually (e.g. source ~/.bash_profile; export PATH (appropriately); /etc/environment modification) in Matlab's command window, which is quite troublesome for future use.

Does anyone have an idea about this ? 
Many thanks, Hzl

**Comment by Hzl-git** [comment]
Hi cookpa,
Thanks for your reply.

Actually, I guess (hope) that this is a permission relative issue.
e.g. in Matlab's command window:

**Comment by cookpa** [comment]
I don't know that those echo statements are helpful. This really Matlab question rather than an ANTs question. I would try following the examples given in the links as exactly as possible, and if that doesn't work, ask the Matlab community for help.

I can tell you that in addition to setting the PATH, you will need to set the variable ANTSPATH for ANTs scripts (like `antsRegistrationSyNQuick.sh`) to run successfully.
