### ISSUE TITLE
ANTSPATH: Why?

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#650]
There are regularly a number of issues that arise due to ANTSPATH being used in Scripts/*.

That leads me to ask: why?

If ANTSPATH were removed from the scripts we could just switch to relying on the ants* tools being in the search path of the environment.

**Comment by stnava** [comment]
make a pull request if genuinely interested.

**Comment by gdevenyi** [comment]
@stnava I'm asking first if this would even be accepted before I go about trying to do this.

**Comment by ntustison** [comment]
I would support something like this since it could potentially simplify code and usage.  My worry would be related to backwards compatibility.

**Comment by stnava** [comment]
a pull request would let us test it

brian

**Comment by cookpa** [comment]
All the cool kids have something similar: FSLDIR, FREESURFER_HOME, HCPPIPEDIR.

I do find it useful to control and report what version of ANTs is getting used. I need to handle multiple ANTs versions, both for testing / development and for managing different research projects, and I need to write scripts that different users will run.

One can as well manipulate PATH instead of ANTSPATH, but you still have to do all the same work in the scripts.

Removing all this and relying on the system PATH at run time would be a big problem for me.

**Comment by gdevenyi** [comment]
Yeah, they do, don't much like that either.

Most clusters and supercomputers use the general solution to this is the environment-modules system (or the rewritten lmod package, https://lmod.readthedocs.io/en/latest/).

Closing WONTFIX
