### ISSUE TITLE
How to modulate the volume changes with registration?

### ISSUE THREAD

**Issue by younghoo** [ANTsX/ANTs#670]
Dear experts, 

I want to account for voxel-wise gray matter volume in my fMRI analysis, so that I segmented T1 image in native space to obtain voxel-wise gray matter volume estimation and then transformed into standard space for statistical analysis. 

Suppose I registered T1 into MNI152 space and generated the Warp.nii.gz/InverseWarp.nii.gz. It is a common practice to modulate the gray matter volume changes caused by non-linear registration. I was told to multiply the transformed gray matter map by the Jacobian determinant of warp field, i.e., ModulatedGM = GM * JacobianDeterminant (The computation of Jacobian Determinant is: "CreateJacobianDeterminantImage 3 InverseWarp.nii.gz jac.nii.gz 0 0"). 

In this discussion (https://github.com/ANTsX/ANTs/issues/640), it was said that if the Jacobian determinant of a voxel is larger than 1, it means that the volume of this voxel expanded after transformation, so that I think the modulation should be like: ModulatedGM = GM / JacobianDeterminant? Sorry that it is difficult for me to understand the maths underlying registration to have a clear idea of these discussions.

I would like to rephrase my question in case that there is ambiguity. How should I compensate the changes of gray matter volume introduced by non-linear registration, assuming that GM is transformed individual gray matter volume and Warp.nii.gz/InverseWarp.nii.gz are the warp/inverse warp field generated by registering individual T1 image (moving image) to standard space (fixed image)? Many thanks!

**Comment by cookpa** [comment]
Here's my take on the right way to do it is following `antsCorticalThickness.sh`, and using the forward warps:

```
${ANTSPATH}/CreateJacobianDeterminantImage ${DIMENSION} \ 
${REGISTRATION_TEMPLATE_WARP} ${REGISTRATION_LOG_JACOBIAN} 1 1
```

So something like:

```
  CreateJacobianDeterminantImage 3 SubjectToTemplate1Warp.nii.gz JacobianDeterminant.nii.gz 0 1
```

Note that `antsCorticalThickness.sh` uses the log, which is often used for TBM because it maps zero volume change to 0 and makes the distribution of percent volume change symmetric about zero. This is convenient for statistical testing.

For intensity modulation of GM probability, I think you want the Jacobian determinant and not its log. 

Why forward warps? Because forward warps are sampled densely in the **fixed** space, which is what you want if you're doing stats in that space. I'm assuming here that you used your template as the fixed image in registration. The warps are sampled densely meaning they store the warp vector from the center of each voxel in the fixed space, to some location in the moving image. This set of vectors is used for resampling the moving image into the fixed space with `antsApplyTransforms`. 



In the case of Jacobians, the volume change that is computed with the forward warps is, for a particular voxel, the estimated (template volume) / (moving volume). For GMP modulation, I think you want to do GMP * (moving volume) / (template volume). So you'd divide the GMP by the output of `CreateJacobianDeterminantImage` with the forward warps.

This isn't as convenient as simply passing the inverse warp to `CreateJacobianDeterminantImage`, but I think it will give a better estimate of the volume change.

**Comment by stnava** [comment]
i added some more here:

https://github.com/stnava/jacobianTests

> In conclusion, the sum of the jacobian within the object in the template
space -- multiplied by the product of the image spacing -- approximates the
volume of the object within the moving image.  Assuming you have only
applied the SyN transformation by itself.

brian

**Comment by younghoo** [comment]
@cookpa Thank you for your help! I would like to confirm that I understand your explanations correctly. 

Assume that a moving image is registered into a fixed image. The forward warp means the warp from moving image space into fixed image space and the inverse warp means the warp from fixed image space into moving image space. 

The jacobian determinant of forward warp represents the (transformed moving image volume)/(original moving volume), so that after transforming moving image into fixed image space, the transformed moving image was divided by the jacobian determinant of forward warp, i.e., (transformed moving image) / (jacobian determinant of forward warp), which would preserve moving image volume while transform moving image into fixed image space.

Theoretically, it seems possible to multiply the (transformed moving image) by the (jacobian determinant of inverse warp), which is though less optimal in practice.

Is my understanding correct in the most general sense?

**Comment by younghoo** [comment]
@stnava Thank you for the help. However, I think your answer is contradictory to that of @cookpa. 

Based on your answer, moving image volume ~= transformed moving image volume (in fixed image space) * jacobian of forward warp. 

I checked the code and data in (https://github.com/stnava/jacobianTests), and the jacobian of registering circ2.nii.gz (a large circle) to circ1.nii.gz (a small circle) would be larger than 1. By referencing to Figure 7 in the ANTs manual, a mapping causing expansion would make jacobian larger than 1. In the test example, mapping a large circle to a small circle should be contraction, and thus jacobian should be smaller than 1. 

I think there must be some misnomers. Hope for some further explanations. Thanks in advance.

**Comment by stnava** [comment]
i think your interpretation of the tests is not correct. I recommend that
you look them over again.

Remember that it matters which image is fixed - in one of the tests, the
circ1 is fixed

https://github.com/stnava/jacobianTests/blob/master/runThis.sh#L4

and it is mapped to circ2.   therefore circ1 *expands* to match circ2.
 thus:

J(x) = Volume( \phi(x ) ) / Volume( x )

is why the volume calculations ( let the math be your guide )  work out.   i

e the sum of the jacobian in the fixed image space within circ1
approximates the volume of circ2.

https://github.com/stnava/jacobianTests/blob/master/rcalc.R#L27-L28

**Comment by cookpa** [comment]
> @cookpa Thank you for your help! I would like to confirm that I understand your explanations correctly.
> 
> Assume that a moving image is registered into a fixed image. The forward warp means the warp from moving image space into fixed image space and the inverse warp means the warp from fixed image space into moving image space.
> 

I think this is the fundamental problem, there is no universal definition of a warp from moving image space into fixed image space. The forward warps will warp a point set from fixed to moving space. This is the operation that is required to produce a deformed moving image in the fixed space.

When `antsApplyTransforms` deforms a moving image in fixed space, it does the following:

1. Define a dense point set (ie, the collection of all voxel centers) in the fixed space.
2. For each point:
  a. Warp the point to moving space using the forward transforms.
  b. Perform some interpolation in moving space (the warped point in moving space will almost certainly not be aligned to the center of a particular voxel).
  c. Place the result in the corresponding voxel of the output image (in the fixed space).
3. Write out the deformed image.

So deforming a moving image to fixed space requires moving a point set in the opposite direction. So any naming convention will cause confusion unless the user understands both the point set and image warping use cases. 

If we were warping a point set from fixed to moving space directly, for example a list of points to measure functional activation, we would use the forward transforms with `antsApplyTransformsToPoints`.

For Jacobians, we are interested in the local volume change introduced by the warp. So we don't consider the affine part, and just pass the deformable part, ie the 1Warp.nii.gz. As in the example above, our objective is to produce an image in the fixed space that contains the local volume change in each voxel. So we use the forward transforms, because those operate on a dense point set in the fixed space.



> The jacobian determinant of forward warp represents the (transformed moving image volume)/(original moving volume), so that after transforming moving image into fixed image space, the transformed moving image was divided by the jacobian determinant of forward warp, i.e., (transformed moving image) / (jacobian determinant of forward warp), which would preserve moving image volume while transform moving image into fixed image space.
> 
> Theoretically, it seems possible to multiply the (transformed moving image) by the (jacobian determinant of inverse warp), which is though less optimal in practice.
> 
> Is my understanding correct in the most general sense?

I stand by what Brian and I wrote above, and I don't think they disagree. 

As I understand the idea, scaling the GMP by the volume change is designed to keep the sum of all GM probabilities constant. So if you have 100 voxels of GM in the moving GMP image, all with intensity 1.0, and your registration scales this region to fill 200 voxels in the template space, the resulting deformed image should have intensity 0.5, such that the total sum of GM voxels remains 100. This makes your VBM on the deformed, modulated images sensitive to both differences in shape (volume change) and appearance (GMP differences in the moving space space).

This is my reading of Ashburner and Friston's paper "Voxel-Based Morphometry - The Methods", which I highly recommend if you are looking to understand this idea.

Regarding the substitution of the inverse warps - it's not possible to reconstruct a warp field accurately given the discretely sampled inverse, for reasons that are explained elsewhere (as in mentioned in the README for Brian's example).

**Comment by younghoo** [comment]
@cookpa @stnava Thank you for your patience and time. The confusion comes from the words (by @cookpa) :"In the case of Jacobians, the volume change that is computed with the forward warps is, for a particular voxel, the estimated (template volume) / (moving volume)." In order to avoid the confusion caused by my inexact wording, I made a simple test using the data provided in (https://github.com/stnava/jacobianTests):

(1) **circ1.nii.gz** is the fixed image, **circ2.nii.gz** is the moving image, **circAjacobian.nii.gz** is the jacobian determinant of forward warp, **CIRC_diff.nii.gz** is the warped moving image.

(2) **circ1.nii.gz** has 368 voxels (1x1x1mm3) and the intensity of each voxel is 1 (like gray matter probability), and thus the volume of **circ1.nii.gz** is 368 mm3. **circ2.nii.gz** has 788 voxels and the volume is 788 mm3. 

(3) The mean jaccobian of **circ1.nii.gz** is 2.14 and 368 * 2.14 equals 787.52, which approximates 788. This demonstrates what @stnava said. 

(4) The mean intensity and voxel size of warped moving image (**CIRC_diff.nii.gz**) are 0.87 and 424, and thus the volume of warped moving image is 368.88, which approximates 368, the volume of fixed image.

(5) The warped moving image (**CIRC_diff.nii.gz**) multiplied by jacobian determinant of forward warp (**circAjacobian.nii.gz**) would result in an image, whose mean intensity, voxel size and volume are 1.85, 424 and 788.64 respectively, thus close to 788 (the volume of moving image).

(6) In voxel-based morphometry, gray matter probability map was first obtained in individual space, and then was transformed into standard space and finally modulated by jacobian determinant  before statistical analysis. This simple test above seemly indicates that if we has transformed the gray matter probability map into standard space, then we should multiply the map by the jacobian of forward warp to compensate the local volume changes. Should we make a multiplication or division?

**Comment by cookpa** [comment]
Additional example here with simplified registration call

https://github.com/cookpa/jacobianExample
