### ISSUE TITLE
antsRegistration segfaulting at initialization 

### ISSUE THREAD

**Issue by shrimpj** [ANTsX/ANTs#684]
Dear ANTS experts,

I attempted to align DTI image (b0) to T1 image using antsRegistration. The original b0 image is 144x144x85 voxel with 1.66x1.66.1.70mm spacing and original T1 image is 256x256x256 voxel with 1x1x1mm spacing. Following error apears, which is identical to the problem that was reported 4 years ago (please see the following link).
https://github.com/ANTsX/ANTs/issues/116
my code was attached
` antsRegistration -d 3 -o [$datadir/ANTS/b02brainmask.nii.gz,$datadir/ANTS/b02brainmask_warp.nii.gz] 
  -n Linear -w [0.005,0.995] -r [$datadir/ANTS/brainmask.nii.gz,$datadir/ANTS/b0.nii.gz,1] 
  -t Rigid [0.1] -m MI[$datadir/ANTS/brainmask.nii.gz,$datadir/ANTS/b0.nii.gz,1,32,Regular,0.1] 
  -c [1000x500x250x100,1e-6,10] -f 8x4x2x1 -s 3X2x1x0mm
  -t SyN[0.1,3,0] -m CC[$datadir/ANTS/brainmask.nii.gz,$datadir/ANTS/b0.nii.gz,1,4] 
  -c [100x70x50x20,1e-6,10] -f 8x4x2x1 -s 3X2X1X0mm 
  -x $datadir/ANTS/ribbon_mask.nii.gz`

=============================================================================
The composite transform comprises the following transforms (in order):
1. Center of mass alignment using fixed image: T_template0.nii.gz and moving image: 1001_3.nii.gz (type = AffineTransform)
=============================================================================
Segmentation fault (core dumped)

error screenshot
![image](https://user-images.githubusercontent.com/16172014/50334111-27d2cd00-04bc-11e9-814c-92c64f25438a.png)
Linux version screen shot
![image](https://user-images.githubusercontent.com/16172014/50334230-8009cf00-04bc-11e9-8b31-435df5c9ae80.png)

Any suggestiona are appreciated!!!!

**Comment by ntustison** [comment]
Fix this option ``-s 3X2x1x0mm`` and try again before we start digging deeper.

**Comment by shrimpj** [comment]
I tried different unit already, but both mm or vox do not work!

**Comment by cookpa** [comment]
You should not use a capital "X", eg `-s 3x2x1mm` not `-s 3X2X1mm`.

I think you might have an older version of the code because I get a specific warning about this, rather than just a seg fault.

Try updating ANTs. You can also try the script `antsRegistrationSyNQuick.sh`, which will generate a command with valid syntax.

**Comment by shrimpj** [comment]
Thanks for the reminding. I changed multiply symbol to lower case which is still not working. The ANTs version we currently used in the lab is 2.2. I also tried to find antsRegistrationSyNQuick.sh which is not exit. I wonder what is the most updated version of ANTs? Thanks

**Comment by cookpa** [comment]
You can checkout the very latest code from Git, but the latest tagged release is from earlier this year:

  https://github.com/ANTsX/ANTs/releases

To compile and set up the scripts etc:

  https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

**Comment by shrimpj** [comment]
Thank you for the promptly reply. The IT technician told me that we updated ANTs in March 2018. I cross-checked the latest code from Git with version we have. They are identical. Thank you again!

**Comment by cookpa** [comment]
The latest code is definitely not identical to that from March 2018. 

Anyway, if you have source code you should have a directory Scripts/ which contains antsRegistrationSyNQuick.sh. If you set your ANTSPATH to wherever your binaries are and run that script, you should be able to do a simple registration. If that works, then the problem is likely somewhere in your specific command above.

If antsRegistrationSyNQuick.sh also seg faults, there may be a problem with your data. We might be able to help with that if you can share the data.

**Comment by cookpa** [comment]
As far as I know there are no current bugs causing seg faults in `antsRegistration`. Will revisit with a reproducible example including data.

**Comment by shrimpj** [comment]
Dear Philip,

Thanks for the reply. I tried nonlinear antsRegistration without rigid body
registration. It worked. I tried rigid body with Affine registration, it
worked. BUT rigid body registration followed by nonlinear SyN[] function.
It's not working. Thank you again! Looking forward to the new example.

Joyce

Philip Cook <notifications@github.com> 于2018年12月27日周四 上午9:57写道：
