### ISSUE TITLE
Possible antsRegistration bug with --initial-fixed-transform and masks

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#769]
The recent problems with registration using masks got me looking into the code involved with masks in registration, and I think I might have spotted a bug here

https://github.com/ANTsX/ANTs/blob/eecaf603e139c91774d8aa92ca4b4e634b6d17cf/Examples/itkantsRegistrationHelper.hxx#L1135-L1142

The `ApplyCompositeLinearTransformToImageHeader` method is called on both the preprocessed fixed image and the mask at each stage. But if the user has not specified masks per stage, then this transform would get applied repeatedly to the same mask image.

I'm not sure how to test this as I have never used this option.

**Comment by ntustison** [comment]
Thanks @cookpa .  I'll try to take a look later today.

**Comment by ntustison** [comment]
Yeah, you're probably right.  I doubt this bug surfaces much, though, if at all, since it applies to the fixed image.  In addition, this code corresponds to an attempt to front load all the linear transforms into the header to save time.  However, it turns out that this doesn't work as one can't put anything but a rigid transform into an itk::Image object.  I never took this code out after my attempt but perhaps I should do that now.  If you don't have any objections, I can work on that.

**Comment by cookpa** [comment]
Sure, if you have time. Thanks for investigating.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/commit/4dda1f75867fd066a52d60bca6d4e76323b833f9

**Comment by cookpa** [comment]
Thanks!
