### ISSUE TITLE
Linux compilation failing on Travis

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#776]
Travis has an older GCC that won't compile ANTs recently

https://travis-ci.org/ANTsX/ANTs/jobs/534217137

I managed to build successfully on Centos 6 with gcc version 7.3.1.

**Comment by ntustison** [comment]
Thanks @cookpa .  So what do we do?  Can we remove this problematic travis build?

**Comment by cookpa** [comment]
It might be possible to update the Travis GCC version, I'll have a go with GCC 5.

**Comment by cookpa** [comment]
OK I can build on GCC 5 with Xenial. I tried to update the travis config but it got confused and ran on my merge commit and not my actual changes. 

Basically I am trying to get it to use Ubuntu Xenial, which has GCC 5 by default. I'm not sure it will work without explicitly setting up a matrix config.

**Comment by cookpa** [comment]
OK it's running now, I will merge to master if successful.

**Comment by cookpa** [comment]
Alas it still seems to run trusty even when I attempt to set Xenial. I am probably doing something wrong but I can't figure it out

 https://travis-ci.org/ANTsX/ANTs/jobs/545371818/config

**Comment by cookpa** [comment]
@gdevenyi Thanks for all your work on this issue. It looks like the Linux build is now good, but there are some timeout failures on the Mac.

https://travis-ci.org/ANTsX/ANTs/builds/548722675?utm_source=github_status&utm_medium=notification

**Comment by gdevenyi** [comment]
@cookpa I see that. It looks like the master branch travis didn't inherit my cache priming from the PR, in fact, it looks like some builds aren't getting cached at all based on the recent commits on master.

Sadly travis seems to be super flaky, see the http errors breaking some of the builds on this commit: https://travis-ci.org/ANTsX/ANTs/builds/549759369.

My next step here is to pare-down the ITK config so that it only builds the things that ANTs actually uses, this should alleviate the timeout issues.

**Comment by cookpa** [comment]
Going to close this, thanks @gdevenyi for your work here

  https://github.com/ANTsX/ANTs/pull/792

and elsewhere to vastly improve the Travis environment for ANTs.
