### ISSUE TITLE
Image intensity becomes blur after rigid alignment

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#783]
Dear Experts,

I have a template image. I want to rigid align an input image I to the template. I want the registered image has the same shape, the position with the template. Hence, I used a rigid and affine transformation. This is my code

`
$ANTSPATH/antsRegistrationSyN.sh  -d 3 -f template.nii.gz -m input.nii.gz -o registed.nii.gz -n 16 -t a`

The original contrast between the regions in the registered image become blur than the original image. What is my issue and how to fix it?

**Comment by ntustison** [comment]
Are you simply referring to the well-known effects of image interpolation?

**Comment by cookpa** [comment]
Try using `antsApplyTransforms` with the `-n BSpline` option.

**Comment by wangken1994** [comment]
Hi, @cookpa 
I tried the `-n BSpline` option, but the intensity contrast wasn't improved.
My procedures are shown below:
**Step1**
```
antsRgistrationSyNQuick.sh \
-d 3 \
-f 1-fa.nii.gz \
-m 2-fa.nii.gz \
-o 2to1 \
-t a
```
**Step2**
```
antsApplyTransforms \
-d 3 \
-e 2 \
-i 2.nii.gz \
-r 1.nii.gz \
-o 2to1.nii.gz \
-n BSline \
-t 2to10GenericAffine.mat
```
**Step3**
```
ReorientTensorImage 3 2to1.nii.gz 2to1Reo.nii.gz 2to10GenericAffine.mat
```
I plot the histogram of the derived FA images:
![image](https://user-images.githubusercontent.com/34388336/59990375-7af92880-9675-11e9-92e9-afd3188ae00d.png)
**Fig1 FA histogram of one slice of 1-fa.nii.gz**
![image](https://user-images.githubusercontent.com/34388336/59990431-b136a800-9675-11e9-9cfc-66f32904c05c.png)
**Fig2 FA histogram of one slice of 2-fa.nii.gz**
![image](https://user-images.githubusercontent.com/34388336/59990494-ec38db80-9675-11e9-8cdb-88ecfddaa287.png)
**Fig3 FA histogram of one slice of 2to1Reo-fa.nii.gz**
It is obvious that the FA intensity of the registered image (2to1Reo-fa.nii.gz) decrease.

**Comment by cookpa** [comment]
It looks to me that the resampled image has a histogram closer to that of the fixed image, which is to be expected. I would also expect tensor interpolation to smooth out the FA image.

If you can upload your images and warps I will take a look.

**Comment by wangken1994** [comment]
[1.nii.gz](https://github.com/ANTsX/ANTs/files/3321482/1.nii.gz)
[1-fa.nii.gz](https://github.com/ANTsX/ANTs/files/3321483/1-fa.nii.gz)
[2.nii.gz](https://github.com/ANTsX/ANTs/files/3321485/2.nii.gz)
[2-fa.nii.gz](https://github.com/ANTsX/ANTs/files/3321488/2-fa.nii.gz)
[2to1Warped.nii.gz](https://github.com/ANTsX/ANTs/files/3321489/2to1Warped.nii.gz)
[2to1InverseWarped.nii.gz](https://github.com/ANTsX/ANTs/files/3321490/2to1InverseWarped.nii.gz)
[2to10GenericAffine.zip](https://github.com/ANTsX/ANTs/files/3321493/2to10GenericAffine.zip)

**Comment by wangken1994** [comment]
**Fig 1 Registered image (2to1.nii.gz)**
![image](https://user-images.githubusercontent.com/34388336/60031899-1f13bb80-96d8-11e9-8628-99642d052a77.png)
**Fig 2 Reoriented registered image (2to1Reo.nii.gz)**
![image](https://user-images.githubusercontent.com/34388336/60031978-41a5d480-96d8-11e9-8b38-76fbbc752266.png)
These two image are too big to upload, you could get them with the uploaded data. @cookpa 
Besides, once adding the `-n BSline` , the noise will occur around the edge of the registered image, and I used mask image to filter them.

**Comment by wangken1994** [comment]
[2to1Reo_maskfilt.nii.gz](https://github.com/ANTsX/ANTs/files/3321540/2to1Reo_maskfilt.nii.gz)
This is the final filtered image.

**Comment by cookpa** [comment]
It might be better to stick to linear interpolation then. The original post did not specify the images were tensors.

I can't see any obvious cause of the intensity change other than aliasing due to resampling. The slices are fairly thick, and the white matter tracts are small. 

I ran the same registration using ITK-SNAP and the resliced image looks pretty similar.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/611507/60034147-f0fe8f00-9677-11e9-84fb-aba86ef0df92.png">

**Comment by wangken1994** [comment]
Thanks for your help! @cookpa

**Comment by John1231983** [comment]
@cookpa : Thanks for value discussion. I think I found the bug. Let I describe my bug. I have 10 images (size of 128x128x256) that will use as input for making a template image. However, the center slice (slice 128) of ten images does not same. For example, the input images are brain image, then slice 128 of first image is brain region, while slice 128 of the second image is black (brain region in the second image may be slice 158).

Hence, the making template image process may be wrong. Do you think that is my problem? Do I need to do pre-processing to make the center slice contains same brain region  for ten images? Does Ants has any function to do it?

**Comment by cookpa** [comment]
The registration transforms are defined in physical space. Therefore you need to know how the physical coordinates align, which you can visualize with a tool like ITK-SNAP

https://github.com/ANTsX/ANTs/wiki/Using-ITK-SNAP-with-ANTs

But as long as the template is well centered, you are probably OK. When it goes wrong, the template will be offset. Fixing this probably won't change interpolation artifacts much.

**Comment by John1231983** [comment]
I see. I just delete all header and convert origin to (0 0 0) that ignored the physical space. Thanks for point out my issue. It is importance issue

**Comment by wangken1994** [comment]
@John1231983 
How did you delete all headers and covert origin to (0 0 0)? Could you list the codes?

**Comment by John1231983** [comment]
@wangken1994 : I just use simpleitk https://simpleitk.readthedocs.io/en/master/Examples/index.html
```
import SimpleITK as sitk
img = sitk.ReadImage(pathtoimage)
img .SetOrigin((0,0,0))
sitk.WriteImage(img, pathtosaveimage)
```
However, @cookpa said that we need to use physical coordinate for making template.

**Comment by John1231983** [comment]
@cookpa : Could you please look at my dataset and my scripts for making template? They are in physical space, so do we need to do  the physical coordinates align as you mentioned?

[reg_T1.nii.gz](https://github.com/ANTsX/ANTs/files/3335712/reg_T1.nii.gz)
[reg_2_T1.nii.gz](https://github.com/ANTsX/ANTs/files/3335716/reg_2_T1.nii.gz)
[reg_3_T1.nii.gz](https://github.com/ANTsX/ANTs/files/3335719/reg_3_T1.nii.gz)
[reg_4_T1.nii.gz](https://github.com/ANTsX/ANTs/files/3335721/reg_4_T1.nii.gz)

My script is 
```
buildtemplateparallel.sh -d 3 -m 30x50x20 -t SY -s CC -c 2 -g 0.2 -i 16 -j 16 -n 0 -o T_ -r 1 *_T1.nii.gz
```
This is image using itk-snap at center slice for first two subjects
![Untitled](https://user-images.githubusercontent.com/24875971/60283252-f50a0580-9932-11e9-95f9-8fbfafdc85a8.png)

**Comment by cookpa** [comment]
It doesn't make sense to say that an image is "in physical space". Every image has a physical space, defined by the image header. It transforms any voxel coordinate (i,j,k) into a physical space coordinate (x,y,z).

When you make a template, it helps to have all the images in the same physical space, so that the registration transforms capture only true anatomical variation and not differences in the image headers. 

If the scan has been acquired properly, the origin of each image (in physical space) should be set to some pre-defined anatomical location, like the anterior commissure. 

To examine alignment in ITK-SNAP, open two images in separate ITK-SNAP windows, and use the crosshair tool to move to some landmark (eg, anterior commissure, AC). The crosshairs in the other window will move to the same location in physical space. If this is very far away from the AC, then you might need to adjust the origins to be consistent.

Again, you want to align the origins in physical space, it doesn't matter what voxel (i,j,k) the AC is at, the important thing is that the physical coordinates (x,y,z) are similar.

If you have already built a template, you can guess from the template output whether you need to worry about this issue. If the registrations to the template look reasonable, and the template is well centered in the image space, then you are probably OK. If the registrations look bad, or the template is shifted out of the field of view, then you may need to adjust the origins.

**Comment by John1231983** [comment]
>When you make a template, it helps to have all the images in the same physical space, so that the registration transforms capture only true anatomical variation and not differences in the image headers.

I attached two header of two images that will use to build template. Do the images in the same physical space? If not, how to align them to  the same physical space? Thanks 
![Untitled](https://user-images.githubusercontent.com/24875971/60388314-b6627f80-9ad9-11e9-8750-1c43f45d5468.png)

**Comment by cookpa** [comment]
They are different but the question is how different they are anatomically, and whether this affects the template.

You can test this by running the template building script for a few iterations with the option `-b 1` to keep all the output from each iteration.

You want to verify two things:

  1. Whether the pairwise registrations work well for all 10 input images

  2. Whether the template has any problematic shifts due to differences in the headers of the input images.

If the registrations work well and the resulting template is not close to the edges of the image volume, then things are working correctly.
