### ISSUE TITLE
Interpret(able) ANTs similarity scores

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#891]
I would like to report the similarity between two images (for context: a functional and a structural projection image).

With something like pearson's r across all values I can just report r, and reasonably expect the reader to know what a good correlation is (i.e. over 0.3 for weak,  over 0.5 for moderate, etc.).
Obviously that's not a very good metric to run on image data, not least of all because it can be strongly affected by the sampling.

Instead, and to give a more complete picture, I would like to report multiple metrics from ANT's `MeasureImageSimilarity` function.

Well, I get something like this (100% sampling):

CC[radius=8]=-0.027098, GC=-0.0384165, MI[bins=32]=-0.04028

As I understand it, closer to zero is better, but is there any way to interpret these values more precisely, or heuristics for what you would call “kind of the same image”, or “really different image”?

**Comment by gdevenyi** [comment]
Hi,

This is a question ANTs folks get asked all the time. Fundamentally, all similarity metrics are biased in some way. Some are normalized like correlations, while others are unbounded, like mutual information. To learn something more about this, try measuring similarity between identical images.

If you want to really get at correspondence in images, you need to do something like dice overlap of "identical" regions as determined by trained experts. Of course, I say "identical" because if you're working with different modalities, you won't be able to strictly delineate an identical region.

**Comment by ntustison** [comment]
And just to clarify a bit, this

> As I understand it, closer to zero is better,

isn't quite accurate.  The similarity metrics in ITK have been formulated such that a decrease in metric value implies increased similarity, not that the values are necessarily closer to zero.

**Comment by TheChymera** [comment]
@ntustison oh, so -0.8 actually means more similar than -0.2 ?

**Comment by ntustison** [comment]
Yes.

**Comment by bheAI** [comment]
But how should I interpretate these values (MI, CC...)? 
In particular, the result of MI value is negative and CC value is integer. 

1. The values obtained from different registration results with CC are all approximate to 0.98
MeasureImageSimilarity 3 1 image1.nii.gz image2.nii.gz {outimage.txt}
how can we consider the registration result to be better.

2. MI value is negative, the results are approximate to -0.6
MeasureImageSimilarity 3 1 image1.nii.gz image2.nii.gz {outimage.txt}
how can we consider the registration result to be better.

3. MeasureImageSimilarity 3 3 image1.nii.gz image2.nii.gz {outimage.txt} 
 this is error :
41419 Segmentation fault      (core dumped) MeasureImageSimilarity 3 3  image1.nii.gz image2.nii.gz
