### ISSUE TITLE
T1w (Partial) SST Registration to a Template  

### ISSUE THREAD

**Issue by asoroosh** [ANTsX/ANTs#908]
Hi Folks, 

I have used `antsMultivariateTemplateConstruction2.sh` to make a single subject nonlinear template for 4 T1w images. Note that T1w images are partial (i.e. missing top of the head, but the cortex is intact), have relatively low contrast and gone through defacing. The template is 1^3mm; 256x256x256. 

Here is my SST template (i.e. the output of antsMultivariateTemplateConstruction2)

![SST](https://user-images.githubusercontent.com/8735002/68204122-3ab09c00-ffbf-11e9-94e6-6e602bec58dc.png)

Now, I want to register the SST with the skull to a 2mm MNI152 template (with skull). I understand that I have to use masks for the moving image (i.e. SST) to account for the partial volume; so I use the following lines:

```
ThresholdImage 3 ${movingImage} ${MASK} 5 Inf

antsRegistrationSyN.sh -d 3 \
        -f ${fixedImage} \
        -m ${movingImage} \
        -x ${MASK} \
        -t s \
	-o ${outputPrefix}
```

And the _registration is failed_ the results are as following (the yellow overlay is the MNI brain, for sanity check):

![SyN-X](https://user-images.githubusercontent.com/8735002/68205720-d263b980-ffc2-11e9-86cd-9a3cb4e56566.png)

Inspired by this link <https://github.com/ANTsX/ANTs/issues/400>, I then tried the following:
```
antsRegistration --verbose 1 \
        --dimensionality 3 \
        --float 0 \
        --interpolation Linear \
        --use-histogram-matching 0 \
        --winsorize-image-intensities [0.005,0.995] \
        --output [${outputPrefix}_X_,${outputPrefix}_X_Warped.nii.gz,${outputPrefix}_X_InverseWarped.nii.gz] \
        --initial-moving-transform [${fixedImage},${movingImage},1] \
        --transform translation[0.1] \
        --metric MI[${fixedImage},${movingImage},1,32,Random,0.25] \
        --convergence [100x50,1e-6,10] \
        --shrink-factors 2x1 \
        --smoothing-sigmas 2x0vox \
        --masks [NULL,$MASK] \
        --transform Rigid[0.1] \
        --metric MI[${fixedImage},${movingImage},1,32,Random,0.25] \
        --convergence [250x250x250x50,1e-6,10] \
        --shrink-factors 2x2x2x1 \
        --smoothing-sigmas 2x2x1x0vox \
        --masks [NULL,$MASK] \
        --transform SyN[0.1,3,0] \
        --metric MI[${fixedImage},${movingImage},1,32] \
        --convergence [50x10,1e-6,10] \
        --shrink-factors 1x1 \
        --smoothing-sigmas 1x0vox \
        --masks [NULL,$MASK]
```
But I still can't manage to get a good registration. Here is results of the above lines (similarly, with the MNI152 brain overlaid in yellow and the grayscale is result of the registration)

![X](https://user-images.githubusercontent.com/8735002/68214315-19f34100-ffd5-11e9-9380-81c7085fdabf.png)

Am I possibly getting something wrong here? Can this be all because of 1mm >> 2mm downsampling?

**Comment by ntustison** [comment]
Have you tried registering skull-stripped versions of both images?

**Comment by asoroosh** [comment]
I was trying to avoid skull-stripping by registering the T1w images with the skull to a template, mask the image by the brain mask of the template and inverse the masked image (i.e. only the brain now) to the SST space.
 
I was hoping this "trick" would buy me some effort and time later in visual quality control since I only had to visually check one registration for both skull-striping and T1w<>MNI registration.

**Comment by ntustison** [comment]
Can you clarify exactly what you're trying to do?  For example, I see that you were able to register the MNI template with ``antsRegistrationSyN`` but then you aren't able to do it with the explicit ``antsRegistration`` call.  Why not just use the first call if you're having success with that approach?

**Comment by asoroosh** [comment]
I'm trying to register a T1 (single subject template 'SST', from antsMultivariateTemplateConstruction2) to an MNI atlas; both have skulls, but the SST has low contrast and has had face and ears removed.  Based on the above, the registration has failed on both calls... the temporal lobe and medial frontal lobe has been squashed, so that to the inferior boundary of the defacing now matches the brain edge. I tried both `antsRegistrationSyN` & `antsRegistration`, both with a mask that reflects the defacing, but both failed.

I have read that skull stripping is advised, but I've had bad luck skull stripping with these images (with antsBrainExtraction.sh and other tools), and I'm processing 1,000's of images so manual brain mask editing isn't practical.  My plan is to do the skull-striping in the template space instead of running on the SST.

My main question is this:  I understood the purpose of the  `--mask` option was to get ANTs to ignore a sharp (but artifactual) boundary.   However, it seems like it's not working here, and the registration is driven by the defacing boundary anyway.  Have I misunderstood what `--mask` is doing?  Or do you have any other suggestions?

**Comment by cookpa** [comment]
If you can share an example data set, I will take a look and see if I can spot any obvious registration issues.

**Comment by asoroosh** [comment]
Unfortunately, the data is locked under a patient confidentiality agreement so I can't share it. I am sorry! But in case if the following further information could be of any help:

Here is the mask of the moving image (SST) I used for the results above:
![SST_MASK](https://user-images.githubusercontent.com/8735002/68479889-54561b80-022b-11ea-8b79-412a654cd8db.png)

I also retired without masking; here is the result of SST(mov)>MNI152(ref) registration (`antsRegistrationSyN `)  if I do _not_ use the moving image mask:

![Screen Shot 2019-11-08 at 13 24 02](https://user-images.githubusercontent.com/8735002/68479955-78196180-022b-11ea-9c2a-5033c106c2fa.png)

Which everything looks perfect but the sagittal side, the motor cortex area which is stretched as expected. 

Let me know if I could possibly provide more information.

**Comment by cookpa** [comment]
As Nick says, getting a brain extraction will likely help a lot, if you can do it. But if you are using an `antsBrainExtraction.sh` type approach, you will need to be able to do a decent registration to a template in order to get your initial mask. It may well be worth spending some effort on using the ants*Net learning tools. 

For registration based approaches, as a first pass, I would recommend the usual things:

1. Good initialization. 
  a. Pad your clipped images by some amount (say 25mm) to avoid boundary issues.
  b. Check that you are getting a good initialization with -r. The center of mass can be thrown off between clipped and non-clipped images. `antsAI` can help with this.

2. Evaluate rigid and affine alignment.

I think you have adapted your command from an intra-subject example, so you have a 
translation and rigid stage, but no affine. This makes sense for EPI <-> T1w but for your use case I think an affine stage will definitely help. For registration to a template, I usually do initialization with antsAI or `-r`, Rigid, Affine, SyN. I typically skip "Translation" because I use antsAI to test different start points, and I find that more robust.

Try to get the rigid and then affine alignment working reasonably well. This can be tested relatively quickly, you can use the output from a rigid stage as input to the affine stage, and so on.


3. Constrain deformable registration

The last image you showed suggests you're getting into the right ballpark. A mask here *might* help. You might also try some regularization eg `SyN[0.1,3,1]`. The downside to this is that it doesn't align the brain as well, but you can do a separate stage with `-t SyN[0.1,3,0]` if you like. The CC metric may also help, though it is slower.

You can specify --masks for each stage of the registration. You would use dummy masks `--masks [NULL,NULL]` until the SyN stage, at which point you could use the real mask.

For the mask itself, you might want to do a closing operation to fill in the gaps between brain and skull, as you want to compute the metric there. The mask might help you once you have a good starting point, to stop the top of the brain being dragged up to cover the stuff that's in the template but missing from the moving image. In my experience a mask is only useful when you can get the solution close to correct, and want to improve it without driving the registration to unwanted features outside of the mask.

**Comment by asoroosh** [comment]
Thank you so much for the detailed reply. 

**_1) Registration of skull-stripped brain_ ==============**
As you mentioned, registration-based skull-stripping methods (i.e. `antsBrainExtraction .sh`) are likely to fail on the data I am working with. In some cases, the FSL bet with tuned parameters was successful but unfortunately, it is not generalisable to tens of thousands of images. 

I have also tried the [ants*Net learning tools](https://github.com/ANTsXNet/BrainExtraction). But I still have a high rate of failure on the images as the test data (low contract, incomplete FOV) is far from the training data (high resolution, complete FOV; IXI, NKI, Kirby, and Oasis). 
Here is some example of the failure in ANTsXNet brain extraction, where the red outline is the extracted brain and the background is the raw image. [Note the crown and the cerebellum where the red line cuts through the tissues and missed the brain border]:

![Screen Shot 2019-12-16 at 10 47 25](https://user-images.githubusercontent.com/8735002/70900855-95430c00-1ff1-11ea-8d8d-f2b9718b2cca.png)
![Screen Shot 2019-12-16 at 10 46 58](https://user-images.githubusercontent.com/8735002/70900863-97a56600-1ff1-11ea-94f6-f05c58cc5c72.png)
![Screen Shot 2019-12-16 at 10 46 49](https://user-images.githubusercontent.com/8735002/70900866-9a07c000-1ff1-11ea-8602-30445170b7b5.png)
**FIGURE 1**

This made me keep trying to find a solution to the registration _with_ skull. 

**_2) Registration with skull_ ==============**
Following @cookpa  suggestions in the previous post:

I padded the moving image by 10 voxels to ensure there is room between the brain and the boundaries:
```
ImageMath 3 ${NonLinSSTDirImg_pad10}.nii.gz PadImage ${NonLinSSTDirImg}.nii.gz 10
```
The original dimension of the moving image:
```
dim1            256
dim2            256
dim3            256
```
The dimension of the padded image:
``` 
dim1            276
dim2            276
dim3            276
```

Then I tried the Rigid transformation [w/out `--masks`] with the following call:

```
antsRegistration \
--verbose 1 \
--dimensionality 3 \
--float 1 \
--collapse-output-transforms 1 \
--interpolation Linear \
--use-histogram-matching 1 \
--winsorize-image-intensities [0.005,0.995] \
--initial-moving-transform [${MNI_2mm_WITHSKULL}.nii.gz,${NonLinSSTDirImg_pad10}.nii.gz,1] \
--transform Rigid[0.1] \
--metric CC[${MNI_2mm_WITHSKULL}.nii.gz,${NonLinSSTDirImg_pad10}.nii.gz,1,10] \
--convergence [1000x500x250x100,1e-6,10] \
--shrink-factors 12x8x4x2 \
--smoothing-sigmas 3x2x1x0vox \
--masks [NULL,NULL] \
--output [${antsRegOutputPrefix}RIGID,${antsRegOutputPrefix}RIGID.nii.gz] \
```

![RIGID-0065x00007](https://user-images.githubusercontent.com/8735002/70896768-3f6a6600-1fe9-11ea-94a1-0a533a8c932b.png)
**FIGURE 2**

So far, everything is nicely done as expected. So I suppose the initialisation has been done successfully and there is no need for a separate `antsAI` call.   

Now, I try the affine [w/out `--masks`] transformation:

```
--transform Affine[0.1] \
--metric CC[${MNI_2mm_WITHSKULL}.nii.gz,${antsRegOutputPrefix}RIGID.nii.gz,1,10] \
--convergence [1000x500x250x100,1e-6,10] \
--shrink-factors 12x8x4x2 \
--smoothing-sigmas 3x2x1x0vox \
--masks [NULL,NULL] \
--output [${antsRegOutputPrefix}AFFINE,${antsRegOutputPrefix}AFFINE.nii.gz] \
```

![AFFINE-0065x00007](https://user-images.githubusercontent.com/8735002/70896897-7d678a00-1fe9-11ea-84dd-164a8c51ca91.png)
**FIGURE 3**

So far, so good. Affine transformation. As suggested, I start the two-stage SyN _with_ mask.

Here is the call and result of `SyN[0.1,3,0]`

```
--transform SyN[0.1,3,0] \
--metric CC[${MNI_2mm_WITHSKULL}.nii.gz,${antsRegOutputPrefix}AFFINE.nii.gz,1,10] \
--convergence [100x100x70x50x20,1e-6,10] \
--shrink-factors 10x6x4x2x1 \
--smoothing-sigmas 6x4x2x1x0vox \
-x [${MNI_2mm_WITHSKULL_MASK}.nii.gz,${NonLinSSTDirImg_mask}.nii.gz] \
```
![SYN0-0065x00007](https://user-images.githubusercontent.com/8735002/70899241-23b58e80-1fee-11ea-8be5-3188718e521f.png)
**FIGURE 4**

Despite the use of mask, `SyN[0.1,3,0]` has stretched the crown. This even gets worse when I try some regularisation with `SyN[0.1,3,1]`:

```
--transform SyN[0.1,3,1] \
--metric CC[${MNI_2mm_WITHSKULL}.nii.gz,${antsRegOutputPrefix}AFFINE.nii.gz,1,10] \
--convergence [100x100x70x50x20,1e-6,10] \
--shrink-factors 10x6x4x2x1 \
--smoothing-sigmas 6x4x2x1x0vox \
-x [${MNI_2mm_WITHSKULL_MASK}.nii.gz,${NonLinSSTDirImg_mask}.nii.gz] \
--output [${antsRegOutputPrefix}SYN1_brain,${antsRegOutputPrefix}SYN1.nii.gz]

```

![image](https://user-images.githubusercontent.com/8735002/70898949-9a05c100-1fed-11ea-9c86-5de9cfbe8d00.png)
**FIGURE 5**

**_3) Skull-stripping with affine_ ==============**

The success (well on couple of problematic images so far) with rigid+affine made me think that maybe it is a good idea to break the registration into two separate parts; 1) I register images _with_ skull linearly (rigid+affine) to the template 2) then I mask the affine transformed image with the template brain mask 3) finally I continue the two-stage SyN on the brain extracted affine transformed images. 

So I use the output of affine and mask it with MNI brain mask:
```
fslmaths ${antsRegOutputPrefix}AFFINE.nii.gz -mas ${MNI_BRAIN_MASK}.nii.gz ${antsRegOutputPrefix}AFFINE_brain.nii.gz
```

And then continue the two-stage SyN with `${antsRegOutputPrefix}AFFINE_brain.nii.gz`:

```

fslmaths ${antsRegOutputPrefix}AFFINE_brain.nii.gz -bin ${antsRegOutputPrefix}AFFINE_brain_mask.nii.gz 

antsRegistration \
--verbose 1 \
--dimensionality 3 \
--float 1 \
--collapse-output-transforms 1 \
--interpolation Linear \
--use-histogram-matching 1 \
--winsorize-image-intensities [0.005,0.995] \
--transform SyN[0.1,3,0] \
--metric CC[${MNI_2mm_NOSKULL}.nii.gz,${antsRegOutputPrefix}AFFINE_brain.nii.gz,1,10] \
--convergence [100x100x70x50x20,1e-6,10] \
--shrink-factors 10x6x4x2x1 \
--smoothing-sigmas 6x4x2x1x0vox \
-x [${MNI_2mm_NOSKULL_MASK}.nii.gz,${antsRegOutputPrefix}AFFINE_brain_mask.nii.gz] \
--transform SyN[0.1,3,1] \
--metric CC[${MNI_2mm_NOSKULL}.nii.gz,${antsRegOutputPrefix}AFFINE_brain.nii.gz,1,10] \
--convergence [100x100x70x50x20,1e-6,10] \
--shrink-factors 10x6x4x2x1 \
--smoothing-sigmas 6x4x2x1x0vox \
-x [${MNI_2mm_NOSKULL_MASK}.nii.gz,${antsRegOutputPrefix}AFFINE_brain_mask.nii.gz] \
--output [${antsRegOutputPrefix}SYN1_brain,${antsRegOutputPrefix}SYN1_brain.nii.gz]
```
Here is what `${antsRegOutputPrefix}SYN1_brain.nii.gz` looks like [Figure 6 the output and Figure 7 with MNI brain template overlaid on the output]:
![Screen Shot 2019-12-16 at 11 39 55](https://user-images.githubusercontent.com/8735002/70904320-f5897c00-1ff8-11ea-82b3-f124d3bbf7af.png)

**FIGURE 6**
![Screen Shot 2019-12-16 at 11 24 48](https://user-images.githubusercontent.com/8735002/70903792-95dea100-1ff7-11ea-84c7-5dc6115732f9.png)
**FIGURE 7**

Again, SyN is trying to stretch the crown upwards and match it to the border of the reference image while ignoring the incomplete FOV (despite the use of `--masks`). 

--

- Am I missing something suggested in your previous instructions? 
- Does section 3 (skull-stripping with affine) make sense?  
- Is there any other way that I could explore to salvage the registration/brain extraction without the need for manual tuning since the dimensionality of the images is on the scale of tens of thousands.

**Comment by cookpa** [comment]
If you want to start the deformable registration from the affine solution you need to include the affine matrix as the initial moving transform. Based on what you wrote I think this is `--initial-moving-transform [ ${antsRegOutputPrefix}AFFINE0GenericAffine.mat`

**Comment by cookpa** [comment]
I think I might have misled you when I said "you can use the output from a rigid stage as input to the affine stage, and so on". You don't want to use the deformed images, rather you want to use the transforms to initialize the solution. So if you have affine alignment working well, you can start deformable registration using the original input image and `--initial-moving-transform [ ${antsRegOutputPrefix}AFFINE0GenericAffine.mat ]` to start SyN. 

To answer your other questions:

_Am I missing something suggested in your previous instructions?_

I'm not sure I agree with your SyN parameters, looks like too much deformation and I don't get why you are doing two sequential SyN stages.


_Does section 3 (skull-stripping with affine) make sense?_

Maybe, but I would warp the template brain mask to the original moving space so that you can do SyN on the original input image with the initial transform. 

I think your main problem at this stage though is not skull, but missing brain. Using the template brain mask will help avoid skull problems, but it won't mask out brain that is present in the template.


_Is there any other way that I could explore to salvage the registration/brain extraction without the need for manual tuning since the dimensionality of the images is on the scale of tens of thousands._

You might try building a template from a sample of your input data, which you can align one time to MNI space. Then you register the clipped volumes to that, and compose the transforms to put the data into MNI space.

**Comment by mydream378** [comment]
For those who have encountered similar issues, please refer to my comments, which would be helpful to fix this issue.

https://github.com/ANTsX/ANTs/discussions/1609#discussioncomment-11636696
