### ISSUE TITLE
Docker container with ANTs 

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTs#914]
I have created an ANTs docker container and a few scripts to help the process. I am not using much ANTs these days, so if anyone wants to give it a try to process anything, it will be good to know. I tried `PrintHeader` and works as expected.
https://github.com/dorianps/docker/tree/master/ants

The container is build with multi-staging to reduce the size. Total size now is 2.5Gb (from 6Gb if developer tools were left in the container)

*Sorry for not using the issue template, did not seem to fit the topic.*

**Comment by gdevenyi** [comment]
Looks good @dorianps . You can rm -rf /opt/ANTs/lib since that's only installed because of how the ANTsR build assumes things right now. That should nicely shrink the build.

**Comment by satra** [comment]
just an fyi that we have been building/distributing containers containing ants from source via [neurodocker](https://github.com/kaczmarj/neurodocker/)  

the current ants download/build spec is here: https://github.com/kaczmarj/neurodocker/blob/master/neurodocker/templates/ants.yaml

**Comment by gdevenyi** [comment]
Hi @satra that script will be broken since the improvements of cmake to properly honour CMAKE_INSTALL_PREFIX, @dorianps 's version does it the supported way now.

**Comment by satra** [comment]
@gdevenyi - is this a cmake issue or an ants issue? i.e. which software's version should we be checking?

ping: @kaczmarj

**Comment by cookpa** [comment]
It's an ANTs issue, it's overall much better IMO. The only annoying thing is that you have to cd to `ANTS-build` to run `make install`. But the make install creates bin/ and lib/ under `$CMAKE_INSTALL_PREFIX`, and copies the scripts too (hooray)

**Comment by gdevenyi** [comment]
ANTs' cmake scripts were updated as of https://github.com/ANTsX/ANTs/pull/841 to stop hard-coding the bin/ and lib/ directories, so that "make install" will work.

A bug in that config was fixed at https://github.com/ANTsX/ANTs/pull/867 to complete the conversion.

**Comment by satra** [comment]
@cookpa and @gdevenyi  - that's great. we will check the git commit hash to determine if we have to use the older or newer form.

**Comment by dorianps** [comment]
Thanks for the input.

@gdevenyi  Your tip shaves another 500mb from the container. Currently the container is 2Gb of which 1.8Gb is /opt/ANTs/bin and 0.2Mb is the system itself.
Is the reverse trick valid for ANTsR too? I am not sure what is needed and what can be removed when ANTs is build inside ANTsRCore, or whether you fixed that with a flag.

Another update:
I updated the dockerfile to make it user-agnostic. This enables a quick conversion of the docker build to singularity, and this can be run on shared environments fine.
Command to convert to singularity:
```
docker run --privileged -ti --rm \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /DATA/dorian/singularity:/output \
      quay.io/singularity/docker2singularity \
      dorianps/ants:latest myants
```
Probably can use the regular docker registry instead of quay, too.

Both the git repository and the dorianps/ants:latest are updated with latest changes.

@satra  how often do you update ANTs in neurodocker? The idea here was to have a solution that is quick to run/build for everyone and have some monthly builds or so.

**Comment by kaczmarj** [comment]
@dorianps - neurodocker generates dockerfiles, so once i update the template to support the updated build process (i.e., `cd ANTS-build && make install`), many versions of ANTs should be build-able. neurodocker can be used to generate the dockerfiles to build ANTs, and then the image can be built from that dockerfile.

another advantage of neurodocker is that it can generate singularity recipes. that's useful for building singularity images too.

i also started this project for pre-compiled binaries of ANTs https://github.com/kaczmarj/ANTs-builds. i use those binaries in neurodocker when users request pre-compiled binaries instead of building from source. i haven't updated the dockerfile to reflect the recent cmake build changes.

last, i think by default, ants will be built as static libraries. building them as dynamically linked will drastically reduce the image size. you would add `-DBUILD_SHARED_LIBS=ON` to the `cmake` command.

**Comment by cookpa** [comment]
@satra @gdevenyi testing now and might not finish today, but I think I figured out how to install ANTs automatically from the SuperBuild. Will update later

**Comment by dorianps** [comment]
@kaczmarj That sounds cool. One thing I still haven't understood is how can someone get the latest ants, i.e., where are the docker images sitting.  Your docker hub has ants builds but they seem to be 1 year old.
https://hub.docker.com/r/kaczmarj/ants/tags

Thanks for the `-DBUILD_SHARED_LIBS=ON` tip.

**Comment by gdevenyi** [comment]
> last, i think by default, ants will be built as static libraries. building them as dynamically linked will drastically reduce the image size. you would add -DBUILD_SHARED_LIBS=ON to the cmake command.

shared vs static won't save you any space sadly. If you static build, you can package *just* the binaries in bin/, as I suggested above. If you go with the shared build you'll need all of libs/ as well. The size of either will be about the same. I suspect the static build (just bin/) will be slightly smaller because the ITK libraries not used won't be linked in and won't be copied into lib

**Comment by dorianps** [comment]
Well, I don't know who is conceptually right, but I tried to build with shared libs and the size has gone down to 500Mb altogether (from 2Gb). A quick test with `PrintHeader` shows it works. Had to add the ants libs in LD_LIBRARY_PATH.

@gdevenyi  you can give it a try with:
```
docker pull dorianps/ants:latest
docker run -v $(pwd):/mydata -it --rm dorianps/ants:latest
```
The singularity file ends up being just 140Mb (!!!), and `PrintHeader` works fine in singularity, too. I can provide the singularity file if needed.

**Comment by cookpa** [comment]
I believe containers are often compressed, and shared libs might compress better. I think Singularity uses squashfs.

But shared libs might just be smaller as there is only one copy of each library routine, rather than having copies in each executable.

Sent from my iPhone

On Nov 19, 2019, at 8:42 PM, dorianps <notifications@github.com> wrote:

﻿

Well, I don't know who is conceptually right, but I tried to build with shared libs and the size has gone down to 500Mb altogether (from 2Gb). A quick test with PrintHeader shows it works. Had to add the ants libs in LD_LIBRARY_PATH.

@gdevenyi<https://github.com/gdevenyi> you can give it a try with:

docker pull dorianps/ants:latest
docker run -v $(pwd):/mydata -it --rm dorianps/ants:latest


The singularity file ends up being just 140Mb (!!!), and PrintHeader works fine in singularity, too. I can provide the singularity file if needed.

**Comment by dorianps** [comment]
@cookpa that is my understanding as well, for example no need to include I/O libraries in each executable, just one for all of them. 

The singularity file size actually matches the docker compressed size in Docker Hub, also 141Mb.

**Comment by gdevenyi** [comment]
Happy to be proven wrong :+1: you make some good points about linking and copies of libraries. I suspect a careful pruning of libs/ could make that smaller still.

@dorianps if you use the new make install method, the RPATH should be set on the executables and LD_LIBRARY_PATH won't be needed. I tested it once when I added it and it worked then...

**Comment by dorianps** [comment]
@gdevenyi  this was a build from this afternoon, and binaries did not work without setting `LD_LIBRARY_PATH`. The dockerfile pulls from git at the moment of the build, so if RPATH was there this afternoon it should have worked.

**Comment by dorianps** [comment]
Btw, the only question looping in my mind is whether there is any overhead or performance hit by using shared libraries. I don't think so, but it would be good to know if anyone ran tests.

**Comment by kaczmarj** [comment]
i don't know specifics but if there is a performance hit by using shared libraries, it is probably minimal. lots of programs use shared libraries. haven't run tests though.

regarding size, i think @cookpa is correct:

>But shared libs might just be smaller as there is only one copy of each library routine, rather than having copies in each executable.

---

>@kaczmarj That sounds cool. One thing I still haven't understood is how can someone get the latest ants, i.e., where are the docker images sitting. Your docker hub has ants builds but they seem to be 1 year old.

the [kaczmarj/ANTs-builds](https://github.com/kaczmarj/ANTs-builds) repository includes links to the statically compiled binaries of various versions of ants, including 2.3.2. i haven't uploaded a docker image recently because that repository is mostly for building static binaries.

**Comment by cookpa** [comment]
I've always steered clear of shared libs for convenience of moving binaries around and to try to have fewer issues loading things on slow NFS servers. But I guess I'll start doing it for container builds. 

I'm holding off on messing with the ANTs install instructions for now. I will try to update the Wiki when I get time. I'd really like to have this workflow:

cmake [opts] /path/to/ANTs
make
make install # installs ANTs

I have a couple of ideas but running short on time to test right now

**Comment by kaczmarj** [comment]
@cookpa - i agree, static binaries are easier to distribute. but if the purpose is to have a container, shared libraries should be fine, because they will move together with the container, and `LD_LIBRARY_PATH` will already be set.

**Comment by dorianps** [comment]
Well... I am more and more convinced of using containers rather than local
installations in the future. Everything can be controlled much more easily,
and we can communicate with researchers using different OS-es knowing that
the tool they use is *exactly* the same (remember Freesurfer's OS dependent
results few years ago?). Moreover, one can pack the container with the
study data and archive it. In recent times I have found myself at least two
times going back to use some tools and finding somewhat different results
on the new computer, while the old one produced the same results (this was
with ASHS and some personal R scripts).

So in principle, if containers (continue to) work well, I think it is worth
keeping up to date images in docker hub so that any user can start using
ANTs tools within 5 minutes and stick to that container throughout the
study. Again, this is more about making things ready for users allowing
anyone to move easily Windows<->Linux as needed.

Will close this issue in a couple of days unless anyone else need it.
