### ISSUE TITLE
allocate error

### ISSUE THREAD

**Issue by fiona3668** [ANTsX/ANTs#917]
**memory allocate error**
when using antsRegistrationSyNQuick.sh, I found there is a error. It says "Failed to allocate memory for image"

Does it means I run out of RAM? How much I need for this?

 * antsRegistrationSyNQuick.sh -d 3 -f ~/0502_VENOUS.nii -m ~/0500_PRECON.nii -o output

 
 * Exception caught: 
itk::MemoryAllocationError (0x7f3a20000940)
Location: "unknown" 
File: /home/fiona/bin/antsBuild/staging/include/ITK-5.1/itkImportImageContainer.hxx
Line: 192
Description: Failed to allocate memory for image.

   

 - Ubtuntu 16.4

 - Type of system:  laptop

**Comment by cookpa** [comment]
It depends on the images. What size are they?

**Comment by fiona3668** [comment]
they are 512 512 80（80mb）,and my pc is 8G.

**Comment by cookpa** [comment]
By default the scripts use double precision (see usage to change to single), so that's 160 Mb, and you'll need several multiples of this for both the images, and all the warp fields. 

You can try 

`free -m`

to see how much RAM is available. The total installed on the machine is an upper limit, but it doesn't mean ANTs can allocate all of that, or even most of it.

**Comment by gdevenyi** [comment]
512x512x80 is *large*, and you get a x3 if you're doing a SyN registration. 8GB is definitely not enough.

**Comment by fiona3668** [comment]
ok thank you guys.
