### ISSUE TITLE
Overestimation of Cortical Thickness (GM) in antsLongitudinalCorticalThickness.sh 

### ISSUE THREAD

**Issue by jckim80** [ANTsX/ANTs#954]
Hello NIck and Brian,

I've run antsLongitudinalCorticalThickness.sh for an ADNI cognitively normal subject.
When I compared the processed images (*BrainExtractionGM.nii.gz and *CorticalThicknessSegmentation), I found that while *BrainExtractionGM.nii.gz is acceptable, *CorticalThicknessSegmentation.nii.gz overestimated gray matter in fusiform gyri resulting in cortical thickness overestimation (please see the attached image).

My questions are:
1) Could you explain why the longitudinal registration algorithm results in this discordance between two images?
2) Do you have an idea to resolve this issue? (I used ADNI MCI Template and for preprocessing N4Biasfield correction and -w 0.25 for Atropos were applied)

Thank you.

Jeongchul.

<img width="1384" alt="Screen Shot 2020-02-19 at 9 58 15 PM" src="https://user-images.githubusercontent.com/48295163/74897388-ef9b7880-5364-11ea-9598-2f13b8f4db1d.png">
).

**Comment by ntustison** [comment]
Hi @jckim80 ,

I'd have to see the entire image contents for that subject.  Can you post it somewhere?

Nick

**Comment by ntustison** [comment]
And also the entire command line used to produce the results.

**Comment by ntustison** [comment]
I just looked more closely at the image on the left.  First, I'd like to see the input image before anything else.

**Comment by jckim80** [comment]
Hi Nick,

Thank you so much for quick response.
I've shared input images and a part of processed results at
https://drive.google.com/open?id=1P0rqwwvD8ut3eZQiwCWC0AiovmRZGbhN
Please let me know if you have any questions.
Thank you.

Jeongchul.

**Comment by jckim80** [comment]
I ran the following command. Here, I used the skull-stripped brain images
instead of the original brain with the skull because the skull stripping
error around the temporal pole area also led to the overetimation of
cortical thickness.

antsLongitudinalCorticalThickness.sh -d 3 -c 2 -j 32 -b 1 -e
$Template_Dir/GT_Brain3.nii.gz -m
$Template_Dir/GT_BrainExtractionMaskPrior3.nii.gz \
-p $Template_Dir/GT_Priors%02dm.nii.gz -f
$Template_Dir/GT_BrainExtractionMask3.nii -w 0.25 -r 1 -o $home/$subj/cth_
$home/$subj/*brain_tp[1-9].nii.gz

**Comment by ntustison** [comment]
Okay, I took a look and everything appears as expected.  A couple things:

* The `*BrainExtraction*` `*CorticalThickness*` segmentation files are temporary files and not meant to be used by the user.  You're certainly welcome to look at them, obviously.  We just don't want the casual user to infer anything about the workings of the program based on those temporary files.  For this particular issue, you should focus on the `*BrainSegmentationPosteriors*.nii.gz` and `CorticalThickness.nii.gz` images.

* The large thickness values are due to the gray matter segmentation crossing over the tentorium. This is a particularly difficult area to segment and this issue is a systematic one that we've known about for awhile but for which we don't have an automatic solution.  

* There's relatively more noise in ANTs cortical thickness estimation compared to FreeSurfer.  This is demonstrated in our plots in our 2014 cross-sectional paper and is something that can be seen in the spaghetti plots that we have in the [repository](https://github.com/ntustison/CrossLong) for our [longitudinal paper](https://www.ncbi.nlm.nih.gov/pubmed/31356207).   It's interesting because of the discussions that this has engendered with reviewers and others regarding what constitutes a good measurement. I mention this because one can easily get distracted by focusing on the accuracy of cortical thickness in a single individual and assume there's something wrong with the scripts where it's really just noise in the data.

**Comment by jckim80** [comment]
Thank you so much for the clarification, Nick.
I understand the difficulty in tissue segmentation around the tentorium.
But, that brings to my attention because fusiform gyrus and inferior temporal regions are AD-signature ROIs that many AD investigators are interested in.

Jeongchul.

**Comment by ntustison** [comment]
Yep, and that's why we recommend that researchers assess pipeline performance across many subjects and not on individuals (E.g., Figs. 3 and Tables 2,3 of our longitudinal paper, specifically as it relates to your regions of interest).
