### ISSUE TITLE
ANTS registration with MI

### ISSUE THREAD

**Issue by lvhiscox** [ANTsX/ANTs#955]
Hello!

I am trying to register a T2 magnitude image to an MPRAGE using the following:

!$ANTSDIR/ANTS 3 -m MI[brain_nat.nii, Diff_topup_bet,1,32] -i 0 -o DiffTopup2brain.nii

with brain_nat being the skull stripped MPRAGE, and Diff_topup_bet being the skull stripped distortion corrected DTI image. I used MI as I read that it works better for intra-modal registrations. (not entirely sure what is recommended for the weight and no of histogram bins?

!$ANTSDIR/WarpImageMultiTransform 3 Diff_topup_bet.nii Diff2Brain.nii -R brain_nat.nii DiffTopup2brainAffine.txt

I then applied the transform as shown as above. However, when I check the images visually, I can see the registration is slightly off.

Do you have any recommendations for optimising this? I have attached the files if that helps (bit difficult to show as image)

[brain_nat.nii.zip](https://github.com/ANTsX/ANTs/files/4247832/brain_nat.nii.zip)
[Diff_topup_bet.nii.zip](https://github.com/ANTsX/ANTs/files/4247833/Diff_topup_bet.nii.zip)

Many thanks,
Lucy

**Comment by lvhiscox** [comment]
[Diff2Brain.nii.zip](https://github.com/ANTsX/ANTs/files/4247841/Diff2Brain.nii.zip)

**Comment by ntustison** [comment]
A couple things:

* Although the ``ANTS`` program sis till usable, we recommend that people use the scripts ``antsRegistrationSyNQuick.sh`` and ``antsRegistrationSyN.sh``.  They "hide" most of the parameters which can cause some confusion.  For your scenario, you can get similar results using:

```
$ antsRegistrationSyNQuick.sh -d 3 -f brain_nat.nii -m Diff_topup_bet.nii -o Diff2Brain -t r
```

Also, instead of using ``WarpImageMultiTransform``, please use the updated ``antsApplyTransforms``.

* You write that the registration is slightly off which is not really enough of a description to diagnose the problem.  However, given the names of the files, I assume you've used FSL and perhaps you're using fslview to view the results for which there can be a potential difference in how the image headers are read.  So, before responding, please check the quality of the registration using something ITK-compatible like [ITK-SNAP](http://www.itksnap.org).

**Comment by lvhiscox** [comment]
Many thanks for your reply - was very helpful.
In terminal I now do:

antsRegistrationSyNQuick.sh -d 3 -f brain_nat.nii -m Diff_topup_bet.nii -o Diff2Brain -t s

I chose "s" as I thought  s: rigid + affine + deformable syn (3 stages) would be more effective. Or, would it be best to stick to an "r"or "a" transform in a intrasubject registration?

Am i correct in thinking this command automatically provides the Diff2brain image (as Diff2BrainWarped.nii) as well as the inverse Brain2Diff  - known as Diff2brainInverseWarp.nii? Thus in this example, there is no specific need to antsApplyTransforms?

Here are the two images overlaid (Diff2Brain and brain_nat) within ITK-SNAP:

![T1](https://user-images.githubusercontent.com/48432262/75218554-9074a400-5768-11ea-9b93-9702e56b4d5d.png)

![T2](https://user-images.githubusercontent.com/48432262/75218548-8ce11d00-5768-11ea-8066-67479ecb47db.png)

As you can see, the corpus callosum is slightly more inferior on the T2 image (Diff2Brain) (i admit it is not the best T2 image). What are your thoughts on this?

Also, does this pipeline use MI or CC?



%Move segmentations into MRE space (nearest neighbour interpolation)
antsApplyTransforms 3 -i aparc+aseg_nat.nii -o aparc+aseg2MagIm.nii -r MagIm_bet.nii -n NearestNeighbor -t [MagIm2Brain0GenericAffine.mat,1] 
%the 1 specifies the inverse transform 
antsApplyTransforms -d 3 -i brain_nat.nii -r MagIm_bet.nii -o brain2MagIm.nii -t [MagIm2Brain0GenericAffine.mat,1]

**Comment by ntustison** [comment]
> Or, would it be best to stick to an "r"or "a" transform in a intrasubject registration?

Yes.

> Am i correct in thinking this command automatically provides the Diff2brain image (as Diff2BrainWarped.nii) as well as the inverse Brain2Diff - known as Diff2brainInverseWarp.nii?

Yes.

> Also, does this pipeline use MI or CC?

MI for both the linear and deformable stages.
