### ISSUE TITLE
About N4 bias field correction 

### ISSUE THREAD

**Issue by wenkesong** [ANTsX/ANTs#975]
In N4, you suppose that the distribution of bias field is Gaussian. Why do you initialize the distribution of bias field like this (the relevant code is in lines 335 through 351 in itkN4MRIBiasFieldCorrectionImageFilter.txx):
![image](https://user-images.githubusercontent.com/49356035/77224238-8ba3e400-6b9e-11ea-9d20-f03a451dd1cb.png)
` vnl_vector< vcl_complex<RealType> > F( paddedHistogramSize,
    vcl_complex<RealType>( 0.0, 0.0 ) );
  F[0] = vcl_complex<RealType>( scaleFactor, 0.0 );
  unsigned int halfSize = static_cast<unsigned int>(
    0.5 * paddedHistogramSize );
  for( unsigned int n = 1; n <= halfSize; n++ )
    {
    F[n] = F[paddedHistogramSize - n] = vcl_complex<RealType>(
      scaleFactor * vcl_exp( -vnl_math_sqr( static_cast<RealType>( n ) )
      * expFactor ), 0.0 );
    }
  if( paddedHistogramSize % 2 == 0 )
    {
    F[halfSize] = vcl_complex<RealType>( scaleFactor * vcl_exp( 0.25 *
      -vnl_math_sqr( static_cast<RealType>( paddedHistogramSize ) )
      * expFactor ), 0.0 );
    }`

**Comment by gdevenyi** [comment]
Rather than copy and pasting some random code, could you please cite the lines in the source?

**Comment by ntustison** [comment]
I agree with @gdevenyi, please copy and paste the link to code.  It's much easier to view in GitHub.  If you don't know how to do it, a quick google search should provide a tutorial.  In the meantime, this part of N4 is taken directly from N3 so I would look at the original [N3 paper](https://www.nitrc.org/docman/view.php/6/880/sled.pdf) as well as the relevant [N3 code](https://github.com/BIC-MNI/N3/blob/master/src/SharpenHist/sharpen_hist.cc) for clarification.

**Comment by cookpa** [comment]
@wenkesong I think you have an older version of the code, because ITK switched from .txx to .hxx files some time ago. 

To reference the current implementation, see the ITK Github

https://github.com/InsightSoftwareConsortium/ITK

If you hit 't' on this page you can search for the file you need. From there you can link to the relevant code as explained here 

https://help.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet

I'd also second @ntustison's suggestion of reading the N3 paper, which explains the basic idea behind the bias correction approach and contains many of the parameter choices later used in the ITK N3 and N4.

**Comment by wenkesong** [comment]
Thanks for your suggestions, I will read N3 paper carefully. As you can see, I'm not very familiar with Github, I'm very sorry for the trouble. Thanks again for your patience and guidance.
