### ISSUE TITLE
antsMotionCorr vs antsRegistration

### ISSUE THREAD

**Issue by AlanKuurstra** [ANTsX/ANTs#983]
Are there any features or outputs available from antsMotionCorr that are not available from antsRegistration? Is there any benefit to using antsMotionCorr over antsRegistration?

Some relevant links I've tried but don't quite answer this question follow:

ANTs Documentation:
https://github.com/stnava/ANTsDoc/raw/master/ants2.pdf
fMRIANTs:
https://github.com/stnava/fMRIANTs
This question:
https://sourceforge.net/p/advants/discussion/840261/thread/9dcb7644/

**Comment by ntustison** [comment]
``antsRegistration`` addresses the pairwise registration scenario.  ``antsMotionCorr`` wraps ``antsRegistration`` functionality for the motion correction case involving more than two images.

**Comment by fuentesdt** [comment]
thansk @ntustison 

it wasn't clear to me that the composite transform was using the neighbor in time information: https://github.com/ANTsX/ANTs/blob/master/Examples/antsMotionCorr.cxx#L859 

i  registered all neighbors in time and then composed my initial transform as the sequence of neighbors. something like:

Starting program: /opt/apps/ANTS/dev/install-dbg/bin/antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output \[Processed/0004/dynamicG1C4incsum.0009,Processed/0004/dynamicG1C4incsum.0009.nii.gz\] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities \[ 0.005,0.995 \] -x \[Processed/0004/anatomymask.nii.gz,Processed/0004/anatomymask.nii.gz\] -r Processed/0004/dynamicG1C4inc.00321Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00320GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00311Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00310GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00301Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00300GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00291Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00290GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00281Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00280GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00271Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00270GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00261Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00260GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00251Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00250GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00241Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00240GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00231Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00230GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00221Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00220GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00211Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00210GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00201Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00200GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00191Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00190GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00181Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00180GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00171Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00170GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00161Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00160GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00151Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00150GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00141Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00140GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00131Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00130GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00121Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00120GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00111Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00110GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00101Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00100GenericAffine.mat -r Processed/0004/dynamicG1C4inc.00091Warp.nii.gz -r Processed/0004/dynamicG1C4inc.00090GenericAffine.mat --transform Rigid\[ 0.1 \] --metric MI\[ Processed/0004/dynamic.0033.nii.gz,Processed/0004/dynamic.0009.nii.gz,1,32,Regular,0.25 \] --convergence \[ 1000x500x250x100,1e-6,10 \] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine\[ 0.1 \] --metric MI\[ Processed/0004/dynamic.0033.nii.gz,Processed/0004/dynamic.0009.nii.gz,1,32,Regular,0.25 \] --convergence \[ 1000x500x250x100,1e-5,10 \] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN\[ 0.1,3,0 \] --metric CC\[ Processed/0004/dynamic.0033.nii.gz,Processed/0004/dynamic.0009.nii.gz,1,4 \] --convergence \[ 100x70x50x30,1e-4,10 \] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox


Is this functionality already in antMotionCorr?


otherwise, some of the time instances work very well, but  some are segfaulting:

Thread 13 "antsRegistratio" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1337700 (LWP 478)]
0x0000000000e64ed7 in itk::DisplacementFieldTransform<double, 3u>::ComputeJacobianWithRespectToPositionInternal (this=0x3c46560, index=..., jacobian=..., doInverseJacobian=false)
    at /opt/apps/ANTS/dev/build-dbg/staging/include/ITK-5.1/itkDisplacementFieldTransform.hxx:282
282           tempPix = m_DisplacementField->GetPixel(difIndex[row][1]);
(gdb)
(gdb)
(gdb)


this is the version i'm using:

$ git log
commit c801b08ac63d8ad6cc50acf710d5e98f4c3e9ecb
Merge: 1195345 33891b8
Author: Philip Cook <cookpa@pennmedicine.upenn.edu>
Date:   Mon Jun 22 14:40:57 2020 -0400

    Merge pull request #1030 from ANTsX/fixStyleCheck

    COMP: Typo in cppcheck config
