### ISSUE TITLE
Cortical Thickness Issue

### ISSUE THREAD

**Issue by daliahr** [ANTsX/ANTs#990]
Hello,

We are attempting to extract cortical thickness from our data, but we are running into some issues. We generated a 20 subject posterior malf image from the OASIS database using the ANTS function antsJointFusion. Now, looking at the cortical thickness images, we are noticing that the occipital region is left out. Does anyone know what might cause this, and how to address it?

Thank you,
Daliah
<img width="1324" alt="Screen Shot 2020-04-08 at 2 36 03 PM" src="https://user-images.githubusercontent.com/63476390/79022604-590d5b80-7b4c-11ea-9c81-30f0ce87f08a.png">

**Comment by ntustison** [comment]
It looks like your template <---> subject registration is bad.  Is this 

"We generated a 20 subject posterior malf image from the OASIS database using the ANTS function antsJointFusion"

the template you used?  

By the way, in the future, always use an ITK-compatible viewer, like ITK-SNAP, before you post an issue just to verify that the issue is not simply a viewer incompatibility problem.

**Comment by daliahr** [comment]
Thanks for your reply!
The issue seems to be with the brain extraction. It seems to be flipping
the brain mask A-P and we are not sure why.

This was the call to the brain extraction routine:

antsBrainExtraction.sh -d 3 -a ../CON/CON_nonBET_297.nii.gz  -m
malf_20subj_brainmask.nii.gz -e ../MYFINAL/MYFINALtemplate0.nii.gz -o
../CON/CON_297

where MYFINALtemplate0.nii.gz was produced with buildparalleltemplate.sh,
and the brainmask is registered to this template.

Thanks again,
Daliah

[image: ANTS-BETissue-2020Apr14.png]

**Comment by ntustison** [comment]
> It seems to be flipping the brain mask A-P and we are not sure why.

A probable issue is the mixing of packages.  ITK/ANTs and FSL utilize the information in the Nifti headers differently.  You can read more [here](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F).  That's why I mentioned not using FSLEyes when looking at ANTs results.

**Comment by daliahr** [comment]
Oh, I see, thank you!

*Daliah Ross* | dross3@mail.yu.edu
Ph.D. Student, Clinical Psychology with Health Emphasis
Ferkauf Graduate School of Psychology, Yeshiva University
Albert Einstein College of Medicine
