### ISSUE TITLE
initialization

### ISSUE THREAD

**Issue by luckyxiaoqi** [ANTsX/ANTs#992]
I use some tips to test initialization such as antsAI or antsRegistration -d 3 -r [ fixed.nii.gz , moving.nii.gz , 1] -t Rigid[0.1] \
-m MI[ fixed.nii.gz, moving.nii.gz, 1, 32] -c 0 -f 4 -s 2 \
-o [movingInit, movingInit_deformed.nii.gz]
,I find after initialization I got images which are back in the last two images,other images are good.

**Comment by cookpa** [comment]
I don't understand the issue here. A reproducible example with code + data would help.

**Comment by luckyxiaoqi** [comment]
I use antsRegistrationSyN.sh then I get poor result. I read #Tips for improving registration results# ,I doubt maybe the initiatization has problem, so I intiliza the data,the command is 
antsAI -d 3 -m Mattes[ /home/ouyangxiaoyun/Downloads/registration/breastRCN/deletebone/raw/17914/Supinecrop2.nii.gz,/home/ouyangxiaoyun/Downloads/registration/breastRCN/deletebone/raw/17914/Pronecrop2.nii.gz] -t Rigid[0.1] -o /home/ouyangxiaoyun/Downloads/registration/breastRCN/deletebone/syN/17914sp/1.mat -v 1
and the result are 

![图片](https://user-images.githubusercontent.com/45393819/79089433-b8e84a00-7d78-11ea-8a40-d40657def186.png)
as the picture show the 127th and 128th pictures are black

**Comment by cookpa** [comment]
Can you share the data?

**Comment by luckyxiaoqi** [comment]
I can send to you by e-mail . Can you tell me you e-mai?

**Comment by cookpa** [comment]
I'd prefer to keep them here so everyone can see and benefit from the answers. If they are under 25Mb, you can upload them here by dragging and dropping into the comment. You can also gzip the images (ANTs can read .nii.gz files) before uploading.

**Comment by luckyxiaoqi** [comment]
[Pronecrop2.nii.gz](https://github.com/ANTsX/ANTs/files/4467927/Pronecrop2.nii.gz)
[Supinecrop2.nii.gz](https://github.com/ANTsX/ANTs/files/4467928/Supinecrop2.nii.gz)
these are  original data.I want to get a better intilization and a good syN transformation.

**Comment by cookpa** [comment]
Thanks. This looks like it will be a hard problem because the images have large deformations, different fields of view, and pretty limited anatomical features. It might need help from landmarking and / or a a transform model other than SyN, but I almost always use SyN so I'm not the best to advise on that.

For initialization, `antsAI` starts from a center of mass alignment, which might not be a good starting point. I was able to get what I think is an OK initialization using ITK-SNAP, doing first a rigid then an affine registration. You can also manipulate these transforms manually. If you save them as ITK transforms you can then use them as initial moving transforms with `antsRegistration`.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/611507/79131695-01066d00-7d77-11ea-94c6-9df01e00e1f8.png">

**Comment by luckyxiaoqi** [comment]
Thanks，I will try it.
