### ISSUE TITLE
Travis builds?

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTs#996]
There are quite a few travis builds [here](https://travis-ci.org/github/ANTsX/ANTs) and the vast majority are passing but the couple that are failing cause the summary report to be one of "failing" (red font/icon) and I would suggest that the failures are issues that we're not going to fix since they're beyond our control.  Do we want to keep it this way or can we have a handful of core builds and the rest be "Allowed failures" similar to ANTsR?

**Comment by gdevenyi** [comment]
The problem with any sort of "allow failures" is we will end up being complacent about whether something is failing due to a real issue, or a Travis issue.

Right now the Travis config attempts to cover the full range of build platforms and systems we would expect ANTs to be used on. If we want to make a definitive statement about what systems are supported, we can switch the "non supported" systems to allow failures.
